### ISSUE TITLE
sample hooks for calling r10k from git

### ISSUE THREAD

**Issue by quaintance** [puppetlabs/r10k#102]
Would like to have some sample code that more intelligently calls r10k via a post-hook on the git server to perform an r10k deploy on a specific environment that is being updated. Today we're very simply saying "ssh $puppetmaster r10k deploy environment -p" as our post hook on git repositories but this is obviously less than ideal.

currently we're using gitolite as our git server but looking at migrating to stash if that makes any difference.

**Comment by acidprime** [comment]
you might want to check out the r10k module [here](https://github.com/acidprime/r10k) as it has an example in files and a in progress webhook as well

**Comment by rnelson0** [comment]
You may be interested in http://philzim.com/2014/05/02/an-automated-r10k-workflow-that-works/

**Comment by rnelson0** [comment]
Check out that workflow, updated, in the form of Reaktor: https://github.com/pzim/reaktor. Do you need more information before this issue is closed out @quaintance?

**Comment by adrienthebo** [comment]
The r10k module has examples of [post-receive hooks](https://github.com/acidprime/r10k/blob/master/files/post-receive) as well as a number of other methods of running r10k, so there are resources available. Since this issue hasn't seen an update in over a year I'm closing it out; please comment if this is still and issue and I can reopen it.
