### ISSUE TITLE
Add support for invalidation of environment cache

### ISSUE THREAD

**Issue by baurmatt** [puppetlabs/r10k#1026]
## Use Case
A production Puppetserver should run with `environment_timeout = unlimited` as described in the [documentation](https://puppet.com/docs/puppet/5.5/configuration.html#environmenttimeout). It would great if r10k could also invalidate this cache for single server setups.

## Describe the Solution You Would Like
Trigger a HTTP API Call as described in https://puppet.com/docs/puppetserver/5.3/admin-api/v1/environment-cache.html#delete-puppet-admin-apiv1environment-cache

```
curl -i --cert <PATH TO CERT> --key <PATH TO KEY> --cacert <PATH TO PUPPET CA CERT> -X DELETE https://localhost:8140/puppet-admin-api/v1/environment-cache?environment=production
```

## Describe Alternatives You've Considered
Wrapper a script around r10k which does this after r10k deployed the code.

**Comment by MAXxATTAXx** [comment]
I would like to see this feature implemented! Currently using a postrun comamnd to execute the refresh. Issue is that currently postrun command exit code different than 0 doesn't do anything so any error that happens inside the script doesn't mark the deployment as failed. This has caused me a lot of issues in the past.

**Comment by Magisus** [comment]
We do something like when using r10k inside PE, but it's easier there because we're already running in the context of the server. We _could_ add something like this, but it would have to be highly configurable, since folks do use r10k without Puppetserver, and we have no way of finding the user's puppetserver, so the user would have to supply all of the relevant info by hand.

That's not a blocker, necessarily. But I think given there are ways to use the post-run script to do this, even if it's not ideal, and that we already have a solution for this in PE that's more tightly integrated with the rest of the system, it's pretty unlikely we're going to get to this. We would, however, be willing to review a PR, I think, if anyone wants to give it a shot.
