### ISSUE TITLE
Allow puppetfile command to configure :cache_root

### ISSUE THREAD

**Issue by hunner** [puppetlabs/r10k#105]
The r10k config file allows for the cache dir to be modified, but this only works with the `deploy` command.

I would really like the `:cache_root` to be modified for `r10k puppetfile install`. Being able to set it to `File.join(ENV['PUPPETFILE_DIR'], '.r10k')` specifically, as this would allow me to use the same r10k cache inside and outside of a vagrant VM when the Puppetfile is located in the /vagrant shared directory.

**Comment by adrienthebo** [comment]
+1. Right now global configuration is tightly coupled with deployment configuration; in order to do what you're describing they'll have to be decoupled. This will be a respectable amount of work and will require a fair amount of restructuring, so while I do want to do this it may have to wait for a while.

**Comment by jfryman** [comment]
+1 to this feature.

**Comment by claytono** [comment]
+1, for the same reason as Hunter.  Having to build the cache each time adds a decent amount of time to a "vagrant up".

**Comment by adrienthebo** [comment]
See also https://tickets.puppetlabs.com/browse/RK-61

**Comment by adrienthebo** [comment]
This is very high up on my priority list, and with luck I'll be able to tackle it within the next few weeks. Because our planning now occurs on JIRA I don't want to duplicate discussion between this ticket and the JIRA one, so I'm going to close this issue in favor of https://tickets.puppetlabs.com/browse/RK-61. Thanks for submitting this!

**Comment by adrienthebo** [comment]
Actually, see https://tickets.puppetlabs.com/browse/RK-120 as it's more specific than RK-61.
