### ISSUE TITLE
There should be a "warn" option for invalid_branches setting

### ISSUE THREAD

**Issue by mwaggett** [puppetlabs/r10k#1055]
Copied from https://tickets.puppetlabs.com/browse/RK-333

"ERROR" is a high-visibility log level that is not appropriate for the behavior of invalid_branches when not correcting branch names.

We should offer a "WARN" level instead. Much easier to filter, and more appropriate for a non-critical informational message about r10k choosing not to take action on a given branch name that doesn't match the required Puppet environment naming convention.

**Comment by mwaggett** [comment]
cc @reidmv

**Comment by mwaggett** [comment]
fwiw, I agree with @Magisus 's comment on the original ticket: 
> Are you proposing that this silently fail to deploy branches that have invalid names? Not sure if that is better...

**Comment by reidmv** [comment]
Responding to the comment, no, the ticket was actually filed more out of the thought that perhaps this occurrence is being logged at the wrong loglevel.

R10k currently allows the following three values for the invalid\_branches config setting:

* 'correct_and_warn' is the default value and replaces non-word characters with underscores and issues a warning.
* 'correct' replaces non-word characters with underscores without warning.
* 'error' ignores branches with non-word characters and issues an error.

I can't find a canonical definition of the log levels but pulling from a decently verbose one:

| Level | Description|
|------|-------------|
| INFO | Info messages correspond to normal application behavior and milestones.  You probably won’t care too much about these entries during normal operations, but they provide the skeleton of what happened.  A service started or stopped.  You added a new user to the database.  That sort of thing. |
| WARN | You use the WARN log level to indicate that you might have a problem and that you’ve detected an unusual situation.  Maybe you were trying to invoke a service and it failed a couple of times before connecting on an automatic retry.  It’s unexpected and unusual, but no real harm done, and it’s not known whether the issue will persist or recur.  Someone should investigate warnings. |
| ERROR | An error is a serious issue and represents the failure of something important going on in your application.  Unlike FATAL, the application itself isn’t going down the tubes.  Here you’ve got something like dropped database connections or the inability to access a file or service.  This will require someone’s attention probably sooner than later, but the application can limp along. |

Error is more serious than Warn. Functionally, for repos where it is _not_ desirable to try and create environments from branch names with non-word characters in them, it can get tedious to have a constant stream of relatively serious Error-level log messages about it.

This ticket is asking for the option, in that circumstance, to set invalid\_branches to:

* 'warn' ignores branches with non-word characters and logs a warning.

**Comment by mwaggett** [comment]
@reidmv Are you saying that it's a common workflow to set `error` and then intentionally use branches with invalid names? I suppose I could see someone doing this if they had long-lived development branches that they don't want to deploy..?

**Comment by reidmv** [comment]
@mwaggett IIRC, you get the errors whether the branches are long-lived or not. If a branch named e.g. FIX-1234 fleetingly exists in your control-repo and an `r10k deploy environment nonprod -p` occurs while it's there, you will get an error logged due to that FIX-1234 branch existing at that point in time.

My position is actually that it was incorrect to have ever logged these messages at the error level. However, it's easier to add a feature 'warn' than to change an existing feature 'error'.

I don't remember exactly what I was doing when I filed the original ticket, but I was working with someone and talking about these messages, and it does come up. I would say that:

1. It is fairly common for users to want to have and use branches which are not intended to be deployable. We even have partial feature support to assist with this by blacklisting; see [ignore\_branch\_prefixes](https://puppet.com/docs/pe/2018.1/r10k_customize_config.html#ignore_branch_prefixes). IMO the _more_ correct feature would be whitelisting, but we don't have that.
2. Our products should be designed to enable desirable workflows, and to not influence users towards undesirable behaviors. It is undesirable to constrain all Git branch naming conventions for development workflow in a repository by Puppet environment naming conventions, for workflows that have nothing to do with git-branch Puppet-environment mapped deployments.

I've actually convinced myself  in writing this that maybe we should not implement a 'warn' option, but instead implement an 'ignore' option that logs the ignored branches at INFO level. It's not even a warning really; nothing is wrong just because a branch called FIX-1234 exists in a control-repo.

**Comment by Magisus** [comment]
So are you saying that there is a workflow where people name their branches invalidly explicitly so that they _don't_ get deployed? That seems...like a hack.

 I know we've talked a lot about how the conflation of git branches and environments causes trouble for people, but it is the world we live in, and while we do, it seems better to me to not muddy the waters further by silently allowing branches that will never get deployed, due to a subtle naming quirk.

If the workflow is real, the ignore prefix seems like a much clearer way to handle it, short of a whitelist like you mention. I'd rather not encourage people to misname their branches just to prevent them being deployed.

**Comment by mwaggett** [comment]
I think I agree with @Magisus - if there's already a way to explicitly mark certain branches as ignorable, that seems preferable to misnaming branches and having them silently not deploy.

**Comment by reidmv** [comment]
To be clear, no variant of this suggestion involves silence. The pain point is that the information is logged at the ERROR level, which indicates "a serious issue and represents the failure of something important". When ERROR level messages are seen in logs this communicates that something is broken and needs to be fixed.

The core assertion I'm making is that Git development workflow can (and in the future _will_) be the primary consideration for branch naming, and that considerations relating to _deploying_ a Git branch as a Puppet environment are secondary to that.

> So are you saying that there is a workflow where people name their branches invalidly explicitly so that they don't get deployed?

No, not at all. I am not saying that people name their branches with explicitly invalidly names so that they can't get deployed. Rather, I'm saying people may use and name many branches _without regard_ for git-branch deployability. Deployability may be a secondary consideration that is relevant for some branches, but certainly not for all.

Even the language in the error we log seems incongruous to the level it's logged at.

```ruby
logger.error _("Environment %{env_name} contained non-word characters, ignoring it.")
```

As a reminder: today you don't have to try and deploy an environment with a bad name to get this error. This error will appear once for every branch in your git repo that includes non-word characters, every time r10k runs, regardless of whether you want to try and deploy any of those branches.

One (or more) of the branches in the repo isn't deployable as an environment, and we have configured Git not to try and coerce it into a form such that it could be.

That's _okay_. That's not a problem. It doesn't indicate something is broken, and there isn't something that needs to be fixed.

Right now the only way to remove the error without adopting undesirable behavior (treat Git development in a bespoke, r10k-specific way) is to set `invalid_branches` to 'correct'.

All that said, this is a relatively unimportant feature request which would be largely rendered moot by eliminating r10k's purview over Git branches entirely, which is the longer term direction. This error vs. warn vs. info issue may be a bit of a bikeshed at this point.

**Comment by reidmv** [comment]
> If the workflow is real, the ignore prefix seems like a much clearer way to handle it, short of a whitelist like you mention. I'd rather not encourage people to misname their branches just to prevent them being deployed.

I agree that a whitelist feature ("deploy _these_ kinds of branches, ignore all others") would be an equally suitable solve for the pain point. Probably better actually, as I imagine that would address the concerns that have been brought up with regards to logging?
