### ISSUE TITLE
add support for using oauth tokens for authentication

### ISSUE THREAD

**Issue by tvpartytonight** [puppetlabs/r10k#1106]
## Use Case
R10k supports both sshkeys and username/passwords embedded in a URL; however, there is no explicit support for using oauth tokens for authentication, as described in [here](https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/). R10k should take a command line arg for an oauth token and use it for authentication; it should not be read from disk or be leaked in a process list.

## Describe the Solution You Would Like
The rugged support is simple enough:

```

# code snippet to generate repo with oauth token
--
creds = Rugged::Credentials::UserPassword.new password: "super-cool-oauth-token", username: 'x-oauth-token'
Rugged::Repository.clone_at('https://github.com/my-cool-org/my-private-repo', Dir.mktmpdir, credentials: creds)
```

## Describe Alternatives You've Considered
Puppet itself is largely interested in rugged support, but shellgit shouldn't be too hard as well, though I haven't really tested it out...

**Comment by Magisus** [comment]
I did some research, and to avoid leaking the secret, I think we should implement this as a flag that takes a file argument. We can then have that read `/dev/stdin` (and implement the `-` convention if we think that'd be good UX), and pass the token on stdin.

I think it might be nice if you could use the same flag for passing either tokens or SSH keys this way (see https://github.com/puppetlabs/r10k/issues/1109). The type of credential required to be passed can be inferred from the form of the URL, so we can give good input validation and nice error messages, without an explosion of new CLI flags.

Doing this as a file arg also gives users the option to use an actual file (rather than stdin) if they want, though for our usecase in PE, we want to avoid writing anything to disk.

**Comment by Magisus** [comment]
Update, we're actually going to focus on implementing this for shellgit first, which is the default here in FOSS r10k.

**Comment by Magisus** [comment]
Change of plans, it turns out it is nontrivial to support OAuth tokens in shellgit, because it expects them to be passed on stdin, which isn't possible with the way we currently shell out to git. Because this work is time-sensitive, we are going to do Rugged support first after all.

**Comment by mwaggett** [comment]
resolved by https://github.com/puppetlabs/r10k/pull/1116
