### ISSUE TITLE
Require a ref, branch, tag, or commit when specifying a module from a git repo in the Puppetfile 

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/r10k#1110]
## Use Case
When a user does not specify a ref, branch, tag, or commit on a module coming from a git repo in the Puppetfile it automatically deploys from the master branch.  

There was a PR up to change that to automatically deploy from the default branch of the git server.  https://github.com/puppetlabs/r10k/pull/1097

Both of these are somewhat magical behaviors that IMO are more likely to cause unexpected results.  

## Describe the Solution You Would Like
Instead the user should be required to specify a ref, branch, tag, or commit and if one is not provided then parsing of the Puppetfile should fail and nothing deployed.  

## Describe Alternatives You've Considered
I've considered the PR above and do not prefer it because it makes it easy for users to get a result that may not be expected.  When the default branch of a git repo changes it can change the catalog applied to agents.  Users should knowingly opt-in to that behavior.  

## Additional Context
The primary reason the above PR was brought up was due to changing from master branch to main across the industry.  Users relying on this default behavior should knowingly opt-in to it by setting `ref => HEAD` in their Puppetfile instead of it just happening when no ref or branch is specified.  

Fwiw, the PR cannot be brought in without a major version because it is a breaking change in behavior.  If we are going to make a breaking change I propose we make a change that improves clarity.

**Comment by trevor-vaughan** [comment]
Honestly, if I'm deploying from a git repo, I expect to get the default branch by default because that's how git works.

If you do this, then I would make a keyword like `__default__` to pull the default branch whatever it happens to be named at the moment.

Also, you could make it opt-in to make it non-breaking.

**Comment by logicminds** [comment]
I would add a feature to Rak10e and other tooling to check for this behavior and warn the user that a default branch is NOT being used.  This won't work in all cases since many don't even know they can use tooling to validate Puppetfile.  

Additionally, if you change r10k you also have to change .fixture.yml too.  We don't want users asking "why do I do this here but not there.

I don't think this feature is worth the time and effort.  R10k has been working like this for 5+ years and the majority of us have never complained.

Now if r10k is hard coded to 'master' that would need to be changed.

**Comment by dhollinger** [comment]
Why not take an extra step and add an option in the r10k.yaml file that can be used to configure an option to use the default branch if none is given? 

This prevents the magic from happening unless a user has specifically configured it to do so in the r10k configuration file.

**Comment by mwaggett** [comment]
Rather than adding a config option to use the default branch, I think we were thinking that folks could just specify 'HEAD' as the ref in their Puppetfile to get that behavior.

**Comment by dhollinger** [comment]
The only problem that we'd have there is that the user would then have to specify 'HEAD' for every repository where they want the default branch pulled down. While I can see the benefits of that, I believe that could end up in degraded UX for many other users that have gotten used to not having to specify the default branch unless they deviate from it.

This is why I thought of a potential config option.

**Comment by logicminds** [comment]
So we can make HEAD the default ref if no ref is provided otherwise users can hardcore HEAD in their Puppetfile.  

Or is this how it works today?

**Comment by dhollinger** [comment]
> So we can make HEAD the default ref if no ref is provided otherwise users can hardcore HEAD in their Puppetfile.
> 
> Or is this how it works today?

Today, it defaults to `master` if no ref is provided

**Comment by mwaggett** [comment]
Changing it to default to `HEAD` constitutes a breaking change, which we are not prepared to make right now.

**Comment by dhollinger** [comment]
Wouldn't requiring a ref also constitute a breaking change?

Is there a change that we can make to account for the change in default branch names that doesn't constitute a breaking change?
