### ISSUE TITLE
R10k should be able to deploy a single module in an environment

### ISSUE THREAD

**Issue by glarizza** [puppetlabs/r10k#112]
R10k can be expensive when doing an `r10k deploy environment -p` or even `r10k deploy environment production -p`.  Sometimes you just want to deploy a change that's been pushed to a single module in a single environment.  Being able to do: `r10k deploy module wordpress --environment development` would be very handy.  And awesome.  It would be 'handsome'.  I just made that word up.

**Comment by antaflos** [comment]
We almost never run `r10k deploy environment -p` since that takes way too long, as you say. Instead we just do `r10k deploy module wordpress` which tries to deploy the module for each environment. If the wordpress module only changed for the `testing` environment it would be updated there and nothing would happen in the other environments. However, R10k will complain when trying to deploy a module in an environment where that module isn't listed in the Puppetfile.

**Comment by glarizza** [comment]
That's a good workaround for now.  @adrienthebo and I were talking about this today, so I wanted to at least file an issue.

**Comment by adrienthebo** [comment]
@glarizza I have this behavior implemented at https://github.com/adrienthebo/r10k/tree/feature/master/gh-112-deploy-module-single-environment that adds a `--environment` option to `r10k deploy module`; please test that code out and see if it'll meet your needs.

**Comment by adrienthebo** [comment]
Merged into master in db12b94; this should be released in 1.3.0.
