### ISSUE TITLE
deployed environments always have an active branch "(no branch)"

### ISSUE THREAD

**Issue by dennisjac** [puppetlabs/r10k#120]
I'm trying to set up a puppet infrastructure using r10k and while the deployment of the environments works the environments don't have a proper branch set:

```
[root@puppet master]# cd /etc/puppet/environments/master/
[root@puppet master]# git branch
* (no branch)
  master
[root@puppet master]# cd /etc/puppet/environments/production/
[root@puppet production]# git branch
* (no branch)
  master
```

This way it's not possible to check in changes and push them upstream.

**Comment by adrienthebo** [comment]
This sounds like it's related to https://github.com/puppetlabs/r10k/issues/97 , could you review that issue and see if it's describing a similar problem?

And for the record, I cannot advise changing, committing, and pushing code as root on a master where r10k has deployed code. In crisis scenarios it might be necessary to do this, but it should be an absolute last resort. It's a much better practice to develop and commit as a non-root user in a non-live directory, push that code to a central repo, and use r10k to pull those changes into a live directory. If there's something about r10k preventing you from doing that I would like to know so that it can be fixed.

**Comment by dennisjac** [comment]
Yes that issue looks like what I'm seeing.

I was following this tutorial: http://terrarum.net/blog/puppet-infrastructure-with-r10k.html

What is the recommended workflow on the development machine? What I'd like to accomplish is to create things on my dev system, make puppet runs to test that the changes work and den push and deploy the changes as you describe above though I'm not sure how exactly to setup the dev system to accomplish that. Do I manually clone each branch on the dev system into /etc/puppet/environments/$env and also manage the modules manually?

**Comment by rnelson0** [comment]
I wrote two articles to address the workflow issues I had and still follow Adrien's guidelines. In summary, commit your changes in a new branch, deploy, and test your dev system against that branch before merging changes back into production or other appropriate branch.

http://rnelson0.com/2014/06/02/puppet-and-git-203-r10k-workflow-new-module/
http://rnelson0.com/2014/06/09/puppet-and-git-204-r10k-workflow-for-existing-module/

Does that help with your concerns?

**Comment by rnelson0** [comment]
@dennisjac I've submitted a PR for some documentation updates related to your questions. Check out https://github.com/rnelson0/r10k/blob/gh-120-workflow-documentation/doc/dynamic-environments/workflow-guide.mkd and https://github.com/rnelson0/r10k/blob/gh-120-workflow-documentation/doc/best-practices.mkd and let me know if they satisfy your questions.

**Comment by adrienthebo** [comment]
Unfortunately this issue is dramatically more complex than it may initially seem. Checking out a commit or tag is generally consistent as HEAD just points to a commit, but checking out a branch means initially creating a new branch and then later doing a pull on that branch. I started on an implementation of this but it got complex and messy very quickly.

In addition, supporting this use case directly conflicts with #47. Git is extremely bad at checking out only parts of a repository; sparse checkouts exist but do not serve to shift the desired subdirectory to the root of the repository. The only way to fake this out is to either do a `git subtree merge` which is deeply flawed for many reasons, or a `git filter-branch` to rewrite all of history, which is equally flawed for different reasons. In either case, these scenarios require drastically altering history which makes the repository worthless for further development. The best approach to this is to stop treating the checked out module as a Git repository and extract/copy the subdirectory into place.

In any case, all of the possible solutions horribly mangle the Git repository in question which makes them unsuitable for use further development. Trying to support actual branch checkouts per this issue and #47 together would require writing monstrous code that would look like it was copied from unspeakably terrible hieroglyphic murals sourced from R'lyeh.

While it would be convenient to use r10k to check out repositories for development purposes, unfortunately it's just not practical to do so; the cost of trying to make this work is enormously greater than asking users to `git clone` repositories. Git repository handling is going to move further away from having checkouts that are usable, which means that there won't be a current checkout at all, let along a checked out branch.
