### ISSUE TITLE
3.10.0 much slower than 3.3.0

### ISSUE THREAD

**Issue by summerm78** [puppetlabs/r10k#1212]
## Describe the Bug
After the upgrade from r10k 3.3.0 to 3.10.0 a deployment is much slower.

r10k version 3.10.0
`time /usr/local/bin/r10k deploy environment -v
INFO	 -> Using Puppetfile '/etc/puppetlabs/code/environments/ocp/Puppetfile'
INFO	 -> Using Puppetfile '/etc/puppetlabs/code/environments/production/Puppetfile'
INFO	 -> Deploying environment /etc/puppetlabs/code/environments/ocp
INFO	 -> Environment ocp is now at d2db54e163ada1c60d283ec32170e7e75bc59078
INFO	 -> Deploying environment /etc/puppetlabs/code/environments/production
INFO	 -> Environment production is now at 0cf390c12184014c1dcf18c712ef174b57bcce18
INFO	 -> Using Puppetfile '/etc/puppetlabs/code/environments/ocp/Puppetfile'
INFO	 -> Using Puppetfile '/etc/puppetlabs/code/environments/production/Puppetfile'

real	4m24.022s
user	0m1.222s
sys	0m0.993s`

Same with version 3.3.0
`time /usr/local/bin/r10k deploy environment -v
INFO	 -> Using Puppetfile '/etc/puppetlabs/code/environments/ocp/Puppetfile'
INFO	 -> Using Puppetfile '/etc/puppetlabs/code/environments/production/Puppetfile'
INFO	 -> Deploying environment /etc/puppetlabs/code/environments/ocp
INFO	 -> Environment ocp is now at d2db54e163ada1c60d283ec32170e7e75bc59078
INFO	 -> Deploying environment /etc/puppetlabs/code/environments/production
INFO	 -> Environment production is now at e817ead7971fc29cbbdfadadda48b9e3330275ed

real	0m16.166s
user	0m0.567s
sys	0m0.243s`

A deployment with version 3.10.0 takes ~4 mins longer than with version 3.3.0

## Expected Behavior
Same time of deployment

## Steps to Reproduce
1. Upgrade to v3.10.0
2. Deploy an environment

## Environment
 - Version 3.10.0
 - Platform RHEL 8.4

**Comment by Magisus** [comment]
This does not reproduce for us generally. A couple of questions:
1) Can you run at a higher debug level (e.g. `--verbose debug1` or even `debug2`) and see if anything jumps out at you as doing a lot more work?
2) Can you try updating to 3.11.0 and see if it stays slow?
3) How would you characterize your environment? Do you have a lot of Forge modules? Git modules? How are your purge levels configured?
4) Are these first-time deploys or deploys of existing environments?

**Comment by summerm78** [comment]
Thanks for your feedback.
1. you'll find the output from debug2 as an attachment.
2. updated to 3.11.0 - same as with 3.10.0
3. In our production env: 60 forge modules, 15 git modules. In our ocp env: 29 forge modules, 6 git modules. We did not configure  the purge levels.
4. These are existing environments.
[r10k_v3.11.0_debug.txt](https://github.com/puppetlabs/r10k/files/7126360/r10k_v3.11.0_debug.txt)

**Comment by justinstoller** [comment]
It looks like fetches are the sources of slowness:
```
[2021-09-08 07:47:38 - DEBUG2] Starting process: ["git", "--git-dir", "/var/cache/r10k/git@igit.internal.our_company.com-our_company-adcsystemd.git", "fetch", "origin", "--prune"]
[2021-09-08 07:47:54 - DEBUG2] Finished process:
Command: git --git-dir /var/cache/r10k/git@igit.internal.our_company.com-our_company-adcsystemd.git fetch origin --prune
Exit code: 0
```
All of them take exactly 15 or 16 seconds according to the log, which seems too consistent to be a repo-specific git issue. It also shows the same delay for both the control repo fetch and the module fetches. However, I'm not seeing a delay like that for any of the local git commands (eg. `rev-parse`) so I don't think it's specific to command execution.

Another way to confirm that would be to do deploys of production and ocp separately and see if the time they take scales with the number of git modules in each env.

----

Between 3.3.0 and 3.10.0 we upped the default thread pool size but I see the initial control repo fetch being slow too, so I don't think that could be it. Unless previous runs of r10k caused your git server to decide your address was potentially mallicious and throttling all subsequent requests (that should be easy to test by switching back to 3.3.0 after having a slow run with 3.11).

Between those two versions we also may re-fetch all the content before purging to see ensure we don't purge content that may have been added during the deploy. However, I would expect it _at most_ to double the time r10k takes, not 17x as you report. It also doesn't look like you've configured purge levels that would trigger that behavior.

----

Those are the only two things that I can think of that would potentially cause issues related to git fetches. I can't validate how many threads you're using because the logs have all but the DEBUG* lines filtered out (kudos to very effectively sanitizing logs, though).

For further trouble shooting could you attempt the command above and see how long it takes (after a slow r10k run)?

**Comment by summerm78** [comment]
I've executed the git fetch command after both r10k versions.
r10k v3.3.0
`
time git --git-dir /var/cache/r10k/git@igit.internal.our_company.com-our_company-adcsystemd.git fetch origin --prune

real	0m15.501s
user	0m0.017s
sys	0m0.018s
`

r10k v3.11.0
`
time git --git-dir /var/cache/r10k/git@igit.internal.our_company.com-our_company-adcsystemd.git fetch origin --prune

real	0m15.472s
user	0m0.019s
sys	0m0.014s
`

We didn't change the threads - it should be (git?) default.

**Comment by justinstoller** [comment]
Was that r10k 3.3.0 invocation equally as slow as the 3.11.0 one? Or half as slow? Maybe most, maybe even all, of the first r10k run succeeds quickly but trips some kind of QoS condition that causes future runs to be slow?

I can't imagine, if git fetches are taking 15 seconds each, that any version of r10k is fast.

**Comment by summerm78** [comment]
Tried it once again with both versions. As you can see in the output - only a uninstall from r10k-3.11.0 is between the two runs.

```
[root@srv-srlp-pm01 ~]# time /usr/local/bin/r10k deploy environment -v --verbose debug2 > r10k_3.11.0.txt 2>&1

real	4m24.279s
user	0m1.305s
sys	0m1.384s
[root@srv-srlp-pm01 ~]# gem uninstall r10k -v '3.11.0'
Successfully uninstalled r10k-3.11.0
[root@srv-srlp-pm01 ~]# time /usr/local/bin/r10k deploy environment -v --verbose debug2 > r10k_3.3.0.txt 2>&1

real	0m16.228s
user	0m0.643s
sys	0m0.277s
```

Both debug-outputs are attached to this post. 

[r10k_3.3.0.txt](https://github.com/puppetlabs/r10k/files/7167178/r10k_3.3.0.txt)
[r10k_3.11.0.txt](https://github.com/puppetlabs/r10k/files/7167179/r10k_3.11.0.txt)

**Comment by justinstoller** [comment]
Thank you so much for bearing with me. I see what happened in that last run. r10k is doing fetches for every module even though you didn't pass `--modules` or `--puppetfile`.

Your 3.3.0 run takes 16 seconds, it spends ~15 seconds fetching the control repo and about one second to realize there's nothing to do and then exits. The 3.11 run also fetches the control repo, but then does fetches for every git repo in each environment (each taking ~15 seconds).

I still need to come up with a reproducer/test case so we don't regress again, but I think I should be able to with this info.

Thanks again, @summerm78 . We'll try to get a new release out with a fix in the next week or so.

**Comment by summerm78** [comment]
Thank you for your replay. I am glad that I could help to find the cause.

If it is not too difficult for a non-developer to do the regression test, I can try it in our environment.

**Comment by summerm78** [comment]
Just updated to v3.12.1 and the issue seames to be fixed in this version.

**Comment by justinstoller** [comment]
Sorry, we saw and commented internally that your issue seemed resolved but forgot to publicly close the issue. Glad it's working now!
