### ISSUE TITLE
mod with git commit ref doing too much work?

### ISSUE THREAD

**Issue by bilco105** [puppetlabs/r10k#127]
Specifying the following in a Puppetfile..;

``` ruby
mod 'postgresql', :git => 'https://github.com/puppetlabs/puppetlabs-postgresql', 
                  :ref => '593ed5b9ddf1223d2bd4da027c22d3720211e42c'
```

Should r10k not just check the modules/postgresql directory exists and the current commit is the one specified?

Instead, it seems to be doing a lot of checks (attached output) which when multiplied over numerous mod lines, takes 4-5x longer than the same file using librarian-puppet.

Debug output: http://pastie.org/9165689

**Comment by adrienthebo** [comment]
This is working as expected. When you use a git module with `:ref` the only way to determine the ref type is with heuristics; for instance `593ed5b9ddf1223d2bd4da027c22d3720211e42c` is also a valid branch name. In the long run r10k may have better heuristics around determining what kind of object a ref is and may be able to perform optimizations on that. However right now you can specify `:commit` instead of `:ref` and r10k will be able to avoid any network calls that are probably the source of your slowdown. See https://github.com/adrienthebo/r10k/blob/master/doc/puppetfile.markdown#git for more information.

I'm closing this issue; please reopen if you still have concerns.
