### ISSUE TITLE
Feature: Ability to deploy tags instead of branches

### ISSUE THREAD

**Issue by zachfi** [puppetlabs/r10k#135]
I'd really like the idea to switch a source from deploying branches into deploying tags.  This would help me track releases of a given module distribution without worrying about which branch I'm working out of, or if the branch is changing over time, and instead track stable releases.

**Comment by zachfi** [comment]
I should note that #101 would also solve my issue, but this might be a more elegant approach.

``` yaml
source:
  foo:
    ..
    ref_method: tag
  bar:
    ..
```

**Comment by adrienthebo** [comment]
Do you want to deploy all tags, or a specific set of tags?

**Comment by naevtamarkus** [comment]
Do you mean "default_ref_method"? It would be great to specify a default, that would be overridden when you specify it in the "mod" line.

In my case, for example, I have the production environment taking the "master" branches of the modules, whereas the testing environment take the "stage" branches... with a few rare exceptions... so having the default_ref_method would be somewhat useful.

**Comment by zachfi** [comment]
The ability to change ref_method on a per source basis.  A default option that could be overridden would solve this.  I don't really care about all tags or a single tag.  Maybe an array of tags?  I don't really know.  I will likely only ever use one at a time, but perhaps the ability to use an older tag in case of issues would be useful.

**Comment by fiddyspence** [comment]
I'd like to add my vote to this as a thing.  Using branches as a way of controlling releases doesn't fit brilliantly with the way version control systems work - being able to release a Puppetfile as a tag would fix that dissonance, remove my need to maintain branches and allow me to release a version by tag.

As background, I'm using r10k in a possibly slightly non-standard way because we're not promoting towards a single production environment, rather a version of a releases is fixed and the environment version number is provided by an ENC and the infrastructure moves along in that way with nodes pinned to a version using the ENC, until they move forward as a result of a release process.  We're also internally multi-tenant, so each environment is made up of n different sets of modules that we integrate before deployment (and we do the actual puppet code deployment using RPMs, do r10k is an intermediate tool).

**Comment by adrienthebo** [comment]
How many tags do you want to have deployed at a given time? Do you want to deploy every tag ever created at all times or do you want to deploy a subset of tags?

**Comment by brettswift** [comment]
There's a chance we could want this as well.   The use case is that we have 20-30 teams all on the same puppet configuration code (which is a different discussion as we could use multiple Puppetfiles instead).   

We'd like the ability to migrate application groups along the 'master' branch (production branch) using tags as well. 

Semantic versioning, and wildcard support seem to make sense to me. 

ie:   1.0.x  

or just an array:  [1.0.1, 1.0.4, 1.2.0, 2.0.0]

This allows big enterprisey processes to "lock down" an application and have infrastructure move alone in a more controlled fashion, per application.    The other way would be managing multiple puppetfile/role/profile projects - which could be more cumbersome for some use cases.

**Comment by crayfishx** [comment]
+1 from me on this request - We have a github repo that contains roles, profiles and a Puppetfile with the names and versions of component modules to set up... our project has a fairly large number of Puppet masters spread out over multiple locations, environments, maturity...etc - we use r10k branch deploy for testing stuff in progress (eg: puppet agent -t --environemnt JIRA-XYZ) but once that's merged in we still want to be able to tag the repo for the official releases that get used.... doing this with branches is possible, but as others have pointed out, not ideal.

**Comment by st33v** [comment]
+1 from a large US financial organization who likes to lock down eeeeeverything to specific versions for audit/compliance/reporting purposes. Branches are nice but not as specific as tags.

**Comment by brettswift** [comment]
+1   but if this feature is implemented,  it wouldn't be helpful to us unless it was supported by the zack/r10k module:  https://github.com/acidprime/r10k

**Comment by crayfishx** [comment]
Is there any progress or feedback on this issue? - Im starting to have to look at workarounds away from r10k to get around it at the moment :(

**Comment by adrienthebo** [comment]
It is not. You can view the current work in flight athttps://waffle.io/adrienthebo/r10k . If you want you can take a stab at implementing a custom source for this; the api is documented at https://github.com/adrienthebo/r10k/blob/master/lib/r10k/source/base.rb and  https://github.com/adrienthebo/r10k/blob/master/lib/r10k/environment/base.rb .

**Comment by adrienthebo** [comment]
I know there's a lot of interest in this feature, but I need to determine the desired use cases and figure out what the correct implementation will be.

One of the implementation behaviors of Git tags is that once they are fetched for a given repository, they are immutable. If a tag is deleted or modified in a remote Git repository, trying to re-fetch tags from that repository will not change the fetched tags. This means that if environments are generated based on Git tags, you will have an immutable and ever growing list of environments. So if you have 100 tags, you'll have 100 environments, and you'll never have less than 100 environments.

Given the above, I am reticent to implement this without firmly establishing that people are willing to accept this behavior. @crayfishx @brettswift @st33v @fiddyspence @xaque208 are you okay with this behavior, or do you need something different?

**Comment by brettswift** [comment]
Caveat: I may or may not be a customer of this approach depending on solving our problem other ways. 

Having said that, if I were to use the git tag approach (here or a future customer) I wouldn't be ok with 100 tags deployed, because I wouldn't want to have to delete tags in order to clean my master up. 

Solving this, my order of preference would be: 
1. enforce semantic versioning, and in r10k.yaml have an optional "minimum version".  Iex: `purge_versions: '<0.1.0'` or regex?.   This may be tricky to implement if you want release candidates.  Ex: 1.0.0_rc1  and sometimes tags have a 'v' prefixing the semantic number.   Could get messy. 
2. list available tags in r10k.yaml (presumably via puppet manifest).  More declarative, but more tedious. 

Just my 2c.  Honestly just as interested in everyone else's use case here.

Sidebar:   Have we thought about the ability to lazy-load tags based on node requests, and have a cache expiry of tags in r10k.yaml?   This may actually be the best way.. 

Edit:  git-hooks could already give you the equivalent of the lazy loading.  It's just a little more complicated than dropping a config value in a yaml file.

**Comment by adrienthebo** [comment]
It looks like either GitHub ate my comment or I failed to send it and then closed the tab. Let's try this again.

To provide additional clarification about tags, it's not that r10k won't implement the re-fetching of tags, it's that it _can't_. Git tags are supposed to be immutable, and the tooling around Git tags make the assumption that once a tag is generated and pushed to the public, it will never change. This has a few implications.

First off, git fetch will only fetch a given tag once. Because tags are supposed to be immutable once a tag is fetched there's no reason to ever change it, again. If a tag is pushed, and then changed and forcibly re-pushed, anyone that fetched the tag before the tag was re-pushed will _not_ receive the updated tag.

Secondly, git fetch will not delete tags without some very specific actions. Running `git fetch --tags --purge` will not delete tags either, because once again Git is making the assumption that once a tag has been released into the wild it's there for good.

Now granted, the Git internals do allow you to delete tags in local as well as remote repos. Pushing an empty ref to a remote tag will delete it, and running `git tag --delete tag` will delete the tag from a local repository. However, as stated above this will not have the same effect as deleting a branch will - for any new fetches the tag will be removed or updated, but existing fetches will not alter their tags. Git makes a lot of things possible, but just because it's possible doesn't mean that it's easy to do or a good idea. Deleting or modifying a tag is about as evil as rebasing and force pushing to a public branch. You can do it, people can recover from the change and life will carry on, but it will require the action of every single person that has cloned your repository and it'll generally make people unhappy.

So the final implication of this is that if you want to generate Puppet environments from Git tags, there are two options - provide a mechanism to select the specific tags you want to deploy, or deploy every single tag ever. The latter option means that you will never be able to reduce the number of environments you have. The former is more viable, but it's definitely variable in how it should be implemented.

Okay, soliloquy over.

@brettswift I like the first option you laid out. It's pretty clean and straightforward. Unfortunately, due to the fact that tags are treated as immutable, if someone mistakenly creates a tag that is misnamed and pushed, then it's permanently invalid and cannot be removed. How should this be handled?

Another option is to select environments based on a regular expression. This is similar to using version specifications via SemVer but is more flexible but might also be more tricky to use. My current idea with this approach is to whitelist based on the regex; whatever tags that match that regex will be created. I do not see any issues with this, but I don't know if this is sufficient for the needs of end users.

To briefly elaborate on generating environments from tags, tags frequently have values that are not valid environment names, namely periods. This means that tag names will frequently have to be reformatted. This does occur to some degree in environments but I see this affecting tags much more heavily. Is this acceptable?

For option 2 laid out by @brettswift, I do plan on implementing this. There are many cases where some code needs to be deployed based on more than just a tag or branch, and only one tag or branch may need to be deployed. Per the comments on GH-101, this is what I currently have in mind:

``` yaml
sources:
  branches:
    # The current Git branch based model
    type: git # git is the default type, but is explicitly put here for the sake of clarity.
    remote: 'git://github.com/myorg/mymodules'
    basedir: '/etc/puppetlabs/puppet/environments'
  tags:
    type: git-tags
    remote: 'git://github.com/myorg/mymodules'
    basedir: '/etc/puppetlabs/puppet/environments'
    # This is what I'm unclear on - how do we select tags?

environments:
  "pinned-environment":
    type: git
    remote: 'git://github.com/myorg/myothermodules'
    basedir: '/etc/puppetlabs/puppet/environments'
    ref: '1.2.7' # could be a branch, or tag, or commit SHA
```

I've looked into combining the deployment of both tags and branches in a single object, and it gets messy. I would much prefer to break these out into separate classes and treat them as different objects for the sake of more maintainable code. Is anyone militantly against this?

The next point worth commenting on is the specification of individual environments. This is extremely easy to implement in the current codebase and allows very fine grained control of environments. However it is a bit more verbose. Since the r10k config file is YAML, this could allow users to use some of the more advanced YAML constructs to reduce duplication, like so:

``` yaml
environments:
  "firstenv": &env # This generates a reference to this hash that we can reuse
    type: git
    remote: 'git://github.com/myorg/myothermodules'
    basedir: '/etc/puppetlabs/puppet/environments'
  "secondenv":
    # This behaves as a hash merge so that we can copy the settings from firstenv and overwrite the
    # settings that vary
    <<: *env
    ref: '64c560a3fc' # pin to a commit
  "thirdenv":
    <<: *env
    ref: 'branchname' # we can also pin to a branch.
```

This is the best idea that I have right now. As with this example as well, is anyone militantly against this approach?

With all of these different constructs combined I think this implements a workflow around git tags that is functional and will not result in unmaintainable code.

Right now the thing I need most is input from the community on use cases and feedback on these examples. I realize that there is a lot of interest in this sort of functionality, but as evidenced above by my long winded spiel on tags, this is not a straightforward problem. The naive and straightforward approach to this is highly degenerate and would be pretty close to useless for any serious use case. I've been holding off on implementing this because I want to ensure I thoroughly understand the problem space and what people need and built an effective solution.

And this is the dump of everything that I've been thinking about on this issue. Your feedback would be greatly appreciated.

**Comment by crayfishx** [comment]
@adrienthebo a few responses from my point of view....

@adrienthebo said

> First off, git fetch will only fetch a given tag once. Because tags are supposed to be immutable once a tag is fetched there's no reason to ever change it, again. If a tag is pushed, and then changed and 
> forcibly re-pushed, anyone that fetched the tag before the tag was re-pushed will not receive the updated tag.

You are right in saying that git tags are immutable, and that they will never change, therefore they do not need updating once deployed (because we can assume that the version will never change) - thats fine.  If someone cuts and deploys a tag by accident then, much like if you released a package onto rubygems or a module to the forge, it's considered "out there" and modifying it is (should not be) an option - just release a fix version - though I see this as one scenario where you might want to forcably delete a tag from git and have r10k recognise that and purge previously deployed versions of it.  That version number however should be considered tainted and never reused.

@adrienthebo went on to say:

> So the final implication of this is that if you want to generate Puppet environments from Git tags, there are two options - provide a mechanism to select the specific tags you want to deploy, or deploy every single tag ever. The latter option means that you will never be able to reduce the number of environments you have. The former is more viable, but it's definitely variable in how it should be implemented.

I think the former personally, regex gives more flexibiity but a standard package dependancy notation (eg: >= 2.0.0, < 4.0.0) would force people into using semantic versioning, but that could be a good thing! It would also be clearer for r10k to know what tags to purge from disk.

Before all of this, @adrienthebo said:

> I know there's a lot of interest in this feature, but I need to determine the desired use cases and figure out what the correct implementation will be.

I can only speak for myself, but I am currently on my 3rd implementation that uses a similar model so it might be similar.  We follow a repo-per-module model for our puppet modules, as is widely advised.  Component modules are versioned using tags and can be referenced as their specific versions with Puppetfile - so far so good.

We then have the concept of a 'environment repo' - I've heard a lot of different names for this, but basically this repo contains a some roles/profiles classes that deal with implementing component modules, and the Puppetfile containing the exact versions of all component modules that these profiles have been written to use.   This environment repo could be distilled down further to just containing the Puppetfile and nothing else, thats not important in the scope of this.... either way, once I have a definitive set of specific versions of my puppet modules, I want to version this and ensure I can roll this exact combination of modules out through my environments in a controlled way.

So to do this  - I want to version my environment repo and then make sure that a subset of nodes use this version of my puppet infrastructure.  The way this is currently done is by tagging the environment repo with a version number (semantic) that then becomes the puppet environment.  Another process exists to control how and when agents are changed to use that version.  This part could be done locally on the agents using MCollective, or centrally from an ENC dictator.

So in my model, all puppet masters have every version of Puppet, and the agents are configured to use a particular version of the puppet code by way of environments.

Another way to think about it is OS patchlevels... If I have 2000 different packages of different versions that collectivly are a particular patch level - I want to have confidence that the patchlevel XYZ that I deployed to staging is the exact same packages that I will deploy to prod.... a patchlevel is effectivly a version of the maturity of my OS - and thats pretty much what the environment repo exists to do.

Im starting to use r10k selectivly to take advantage of the Puppetfile functionality but looking to write workarounds to enable the above and not have r10k manage the environment - so I'd love to see r10k be able encompass the whole process.  Personally, I find the environment per branch feature a bit useless outside of a vagrant environment - deploying tags is the win IMO.

Craig

**Comment by adrienthebo** [comment]
>  though I see this as one scenario where you might want to forcably delete a tag from git and have r10k recognise that and purge previously deployed versions of it.

Because Git does not automatically do this, r10k will not automatically do this either. If it's necessary then a user can go in and prune tags by hand, but this should not happen in normal operations.

There's one case where r10k will delete tags, but that's when a git remote is switched from one repository to another. Tags aren't namespaced for repos so switching to a different remote could pull in an entirely isolated set of tags. In this scenario r10k blows away tags wholesale, but that's the only case where it's a normal use case.

> a standard package dependancy notation (eg: >= 2.0.0, < 4.0.0) would force people into using semantic versioning, but that could be a good thing! 

Should improperly formatted tags be ignored outright?

**Comment by crayfishx** [comment]
> > though I see this as one scenario where you might want to forcably delete a tag from git and have r10k recognise that and purge previously deployed versions of it.
> 
> Because Git does not automatically do this, r10k will not automatically do this either. If it's necessary then a user can go in and prune tags by hand, but this should not happen in normal operations.

OK - I don't think thats a major point.  If we go down the route of specifying a regex or version ranges of tags that we want r10k to deploy, maybe it should purge any previously deployed puppet environments that don't match the criteria? 

> > a standard package dependancy notation (eg: >= 2.0.0, < 4.0.0) would force people into using semantic versioning, but that could be a good thing!
> 
> Should improperly formatted tags be ignored outright?

I would say yes - but then, perhaps handcuffing people into following semver tag versioning is a little too presumptuous and maybe simply a regex would be better...  Personally I'm in favour of using semver version numbers as tags, and ignoring anything else.  But my problems go away with whatever approach gets taken ;-)

**Comment by crayfishx** [comment]
@adrienthebo just FYI, this is a temporary (I hope) workaround that I am using at the moment - https://github.com/crayfishx/puppet-tags/blob/master/files/puppet_tags.rb  -  it would be nice to be able to do the same natively from r10k rather than wrapping it in this..

**Comment by benpriestman** [comment]
I'm interested in this as well. I see this issue is tagged as 'ready' but that it has also been removed from the 1.5.0 milestone. Does this mean it's a candidate for 1.6?

**Comment by stepanstipl** [comment]
+1 Hi, also very interested... what's current status on this? As it's marked as ready...

@adrienthebo 
- **immutable**: completely fine, I would not expect otherwise given how git works
- **selecting tags**: I would go for regexp - while going via semantic version selector as `>=1.2.3` would be fine in my use case (that's what we follow with our tags), I feel like regexp gives you flexibility also for use cases where you decide to use different naming convention
- **env naming**: same behaviour as with branches. e.g. `1.22.33` will become `1_22_33`, is completely fine

thanks

**Comment by crayfishx** [comment]
+1 with what @stepanstipl said - is this any closer to being released?

**Comment by adrienthebo** [comment]
@crayfishx unfortunately I no longer have the option to unilaterally implement features in r10k, since it's a Puppet Labs project and not my own side project. That being said, I am pushing to get this in 2.1 - as always I can't make promises but I am pushing for this.

**Comment by teriyakichild** [comment]
+1

**Comment by antevens** [comment]
+1

**Comment by nickithewatt** [comment]
+1

**Comment by thejandroman** [comment]
Is this being tracked in [JIRA](https://tickets.puppetlabs.com/browse/RK/)? I couldn't find a corresponding ticket in there.

**Comment by scotje** [comment]
I didn't find one either, I've added https://tickets.puppetlabs.com/browse/RK-201 to track it.

**Comment by zachfi** [comment]
There was a jira ticket in the code management project.  Not sure if it was public.

**Comment by elliottsam** [comment]
+1

**Comment by maartensl** [comment]
The ability to have r10k deploy a tag is definitely useful to us as well. For our use case we don't care if it is treated in the same way as a branch, so the following usage is perfect:

`r10k deploy environment <tag name>`

Although I'm conscious this may not cover some of the concerns discussed above, the following hack does the job for us. We're running gem version 2.1.1 and I've changed the `branch_names` method in `lib/r10k/source/git.rb` to be:

```
  def branch_names
    opts = {:prefix => @prefix, :invalid => @invalid_branches, :source => @name}
    (@cache.branches.concat(cache.tags)).map do |bt|
      R10K::Environment::Name.new(bt, opts)
    end
  end
```

I'd be curious to know if this could break any other functionality.

**Comment by scotje** [comment]
I think one of the concerns about deploying tags automatically was that, by definition, they will continue to grow unbounded and eventually Puppet is going to be sad about the number of directory environments you have. There are some possible solutions involving things like version ranges or explicit lists of tags to be deployed but I think all of the proposed approaches have various flaws or limitations.

The idea of tags only being deployable by an explicit `r10k` invocation with the given tag name (and never trying to automatically deploy or update) is interesting though. Obviously you would have to write your own tooling around that to automate anything but maybe that's acceptable for the proposed use cases?

**Comment by maartensl** [comment]
Our use case may not be the norm, because we run a Puppet Server per environment. As a result we can usually purge directories other than the explicitly r10k deployed environment (be that a branch or a tag). So our Puppet does not become sad :-)

I've done some testing around it, and it works perfectly well for our use cases. However I can see how, if you expect r10k to deploy all environments automatically in the background, rather than being explicit, that you might then have a lot of redundant directories hanging around.

A useful way around that could be to introduce a cli option such as `--include-tags`,  which then activates the required behaviour; or if the majority of people are using r10k in the explicit mode already, make it the default and have `--exclude-tags` as an option.

**Comment by antevens** [comment]
I think the only sensible solution is to make tags only available by explicitly invoking r10k with the flag name or alternatively --include-tags in which case I think the logical solution is to look up which hash each tag points to, making a separate directory per hash and using symlinks per tag name to each hash.

In our case we wan't to be able to track our source code repos using tags along with our 50 or so puppet repos, we use these both for our SaS servers as well as bundling the source / puppet code up and shipping it to our customers for each release. When a customer reports an issue we wan't to be able to reproduce the exact combination of our source and puppet repo so it's important for us to be able to rebuild a server using the exact same tags as before. 

Currently we have a primary puppet repo and for every tag in our source we create a branch in the primary puppet repo, the puppet repo itself contains a Puppetfile which then points to tags in all the other puppet repos.

**Comment by KZachariassen** [comment]
Status on this - We really need semantic version support

**Comment by brettswift** [comment]
I don't know about everyone else but I'm not sure I want this anymore. At
least not on by default.

This is why.

We are doing this by creating a branch from tags we want available.
Release/1.0.0 for example.

We release weekly. Which is a lot of tags for r10k. So do we have LTS
releases for testing in our pipeline? How do we de mark them?

I'd love this feature if the workflow of marking tags as released would be
as simple as creating and deleting a remote branch.

I guess it's moving slowly because of a lot of the contentious use cases we
all have.

We might not use it if the workflow is done easier with branches.

**Comment by zachfi** [comment]
@brettswift Probably not by default, but the initial idea proposed here would require the configuration be tuned for this type of workflow, as different environment have different requirements.

I still think some way to tell r10k to deploy the 5 most recent tags would be useful.  Obviously letting r10k deploy an unbounded set of tags doesn't sound like the right choice.

What data is required here to move this along?  It doesn't seem that two years of comments and dreaming in a box is helping.  There are lots of special use cases for the different environments that we can dream up and avoid action, but is there a 'good enough' solution that can help move the conversation forward?

The suggestion above by @antevens seems smart to me.  Allow the user to specify a set of tags or refs or whatever.  Then I can just | `sort | head -n 10` or whatever to get the command to execute and receive my basic desire, but at least I'm empowered to do something that suits me, and doesn't break anyone else.  `r10k deploy environment tag:1.0.0 -v` looks like a sensible command, or perhaps `r10k deploy tag 1.0.0 -v` or some such.  Just thinking aloud.

**Comment by brettswift** [comment]
Yea I'm just thinking aloud here too.

Generally speaking I think deploying one off tags are good. But guys like
us that still run a cron job (for various reasons) as opposed to a git hook
- the purge environments comes into play.

The most interesting part to me would be tag environment lifecycle. More
interestingly removing them.

We also don't have to make everyone happy but a first pass I would agree -
make it light and flexible.

**Comment by disassembler** [comment]
I agree with @antevens and @xaque208. I don't particularly want to automate deploying every new tag pushed, but being able to override a specific env with a specific version is useful, for example if I need to rollback a production change quickly. I like the syntax `r10k deploy tag 1.0.0 -v`.

**Comment by st33v** [comment]
puppet is dead to me. I don't care

**Comment by antevens** [comment]
It's not like the world has been taken over by kernel backed chroot environments displacing VMs ... ohh wait never mind
