### ISSUE TITLE
puppet enterprise vagrant r10k sandbox development environment with geppetto

### ISSUE THREAD

**Issue by pearcec** [puppetlabs/r10k#138]
I have setup a working sandbox with
- Virtualbox
- vagrant
- vagrant-pe_build
- vagrant-hosts

This builds a perfect master agent sandbox using r10k to deploy a puppet sandbox environment.  I am creating by hand a sshfs to mount the root@master.local:/etc/puppetlabs/puppet/environments/sandbox/modules/ environment.  I want to use geppetto to import all the projects and export it as a working set for the team.  r10k uses the concept of a remote "cache" to fetch stored objects which eliminates duplication and speeds it up.  It also leaves the clone on a "(no branch)" checkout.  When I go to import the project via geppetto the cache is not on my hypervisor where I am editing.  So it essentially non functional.  I can try to fix the clone, but I am hoping there is a better automated solution before I script something.
1. Does anyone have a better methods for sshfs?  I tried vagrant-sshfs but that didn't work
2. Is there a better way to use r10k to create a working copy?
3. Is there a better sandbox environment?

**Comment by adrienthebo** [comment]
With respect to the git checkouts being based on a ref, does GH-97 properly cover that issue?

**Comment by adrienthebo** [comment]
To follow up on this, the reason that the repositories are non-functional is that right now only a single git alternate repository is specified for any checked out repository. Since all of the actual git objects associated with the repository are in the alternate object directory, when the path doesn't exist git suddenly has no history. It's possible to specify multiple alternate object directories for git, but this will require some thought for r10k to include.

**Comment by pearcec** [comment]
If I understand it correctly, Linking to GH-97 is probably a good call.  I would likely go the puppetfile option to get my checkouts and call it a day.  I am reading code now.  Seems it isn't functional at the moment.

UPDATE: I did get puppetfile install to work.  It effectively does the same thing with the alternate repo cache.

**Comment by adrienthebo** [comment]
Per the conversation in GH-97, it's not really possible to check out environments and modules via Git in a sane way that also allows them to be updated in a reasonable manner, and can support the `:path` option to check out a subdirectory. Since this issue has been sitting for more than a year and there's not been any follow ups, I'm going to close this out. If this issue is still active please comment on it and we can reopen it. Thanks!
