### ISSUE TITLE
r10k should (optionally) update environment only when branch changes occur

### ISSUE THREAD

**Issue by eops-wedgwood** [puppetlabs/r10k#139]
According to the output of `--verbose debug1`, r10k rebuilds environments _every_ time `deploy` is run. This is a simple way of ensuring that environments are up-to-date while also ensuring that local changes are overwritten.

In an environment where changes to the puppetmaster are well-controlled, this behavior is undesirable because:
- Large environments make include hundreds of modules. Updating every one is inefficient and slows down the deploy process.
- If all environments are blindly updated, it's challenging to detect (and possibly alert) when a change occurs.

Both of these are important to us. We would like to run environment updates very frequently on several puppetmasters (and we may have dozens of upstream repos with several branches each). We would also like to monitor changes and kick off catalog compilation jobs when they occur.

The ideal behavior for us would be:
1. Fetch all configured puppet repos
2. For all branches that have changed, perform a checkout
3. Examine all Puppetfiles
4. Fetch all module repos
5. Check out only modules that have changed, taking into account refs in each Puppetfile

Without looking at the existing code, I would assume this means adding tracking the commit for each HEAD for each configured ref.

I think it would be possible to support this as optional behavior, defaulting to the old behavior of overwriting environments regardless of upstream changes.

**Comment by adrienthebo** [comment]
r10k provides fine grained controls over what code gets deployed (https://github.com/adrienthebo/r10k/blob/master/doc/dynamic-environments/usage.mkd), so you can update a single environment, a single environment and all modules for that environment, a module in all environments, and in 1.3.0 a single module in a single environment. If you need to have exact control over what gets deployed, the existing commands should allow you to achieve this.

Do you have a hard requirement that this all should be done automatically?

**Comment by mwedgwood-rmn** [comment]
I could be missing something subtle there. From what I see in the logs, modules are checked out (written to the filesystem) even if there are no changes in the upstream repo. This seems to happen no matter what ref is specified in the Puppetfile. For example, if I specify "4.1.0" as the tag I'd like to use for a module, each time I run `r10k deploy`, r10k will perform a checkout to the environment even if there have been no commits to that tag since the last run.

In the debug output, this shows up as something like this:

```
[R10K::Task::Module::Sync - INFO] Deploying stdlib into /srv/puppet/environments/master/modules
[R10K::Git::WorkingDir - DEBUG1] Execute: git --git-dir /srv/puppet/environments/master/modules/stdlib/.git fetch --prune cache
[R10K::Git::WorkingDir - DEBUG1] Execute: git --git-dir /srv/puppet/environments/master/modules/stdlib/.git show-ref --tags -s 4.1.0
[R10K::Git::WorkingDir - DEBUG1] Execute: git --git-dir /srv/puppet/environments/master/modules/stdlib/.git show-ref --tags -s 4.1.0
[R10K::Git::WorkingDir - DEBUG1] Execute: git --git-dir /srv/puppet/environments/master/modules/stdlib/.git --work-tree /srv/puppet/environments/master/modules/stdlib checkout --force c1610f71ec45fb6503e063851f37eb478445678f
```

It's that last line I'm focused on. If I wanted to, for example, trigger a catalog compile on environments that have changed, I'd have trouble knowing because the `checkout` causes write activity in a repo at every `deploy`.

(sorry for the github account switch, I filed this issue from the wrong browser window)

**Comment by adrienthebo** [comment]
If you're specifying a tag or commit, the checkout is spurious and will not change any files on disk. Right now r10k doesn't have sufficiently elaborate heuristics to be able to determine what type of object a reference is, so if `:ref` is specified r10k will take the safest route by trying to update it even if it's a static value. You can alternately specify `:tag` or `:commit` instead of `:ref` to avoid this entirely, per the documentation at https://github.com/adrienthebo/r10k/blob/master/doc/puppetfile.mkd#git .

**Comment by mwedgwood-rmn** [comment]
I missed this comment somehow. Thanks for pointing out those other args. I'll give them a try.
