### ISSUE TITLE
How to install a snapshot version of r10k from behind a proxy?

### ISSUE THREAD

**Issue by timidri** [puppetlabs/r10k#142]
Hi,

I am using Puppet Enterprise and my machine is behind a corporate proxy. I am trying to install the r10k version from the 1.3.x branch to test the new subversion features. I am getting stuck at various components not supporting http_proxy and https_proxy environment variables. Do you have any tips on how to do this? Thanks in advance.

**Comment by adrienthebo** [comment]
Environment variables should be passed from r10k to child processes; I'm surprised that this is an issue. Someone will need to drop into the source code and see why variables aren't being passed through.

**Comment by ahmet2mir** [comment]
With

```
http_proxy="http://login:password@server:port" r10k deploy environment -p
```

it work's

EDIT: Work without login/password.

**Comment by timidri** [comment]
What I meant is not deploying an environment but installing r10k using bundler.

**Comment by adrienthebo** [comment]
Looking at http://blog.lfsolutions.net/use-rails-bundler-behind-proxy/ indicates that this might be an issue with environment variables interacting with sudo; how are you trying to install r10k?

**Comment by rnelson0** [comment]
@timidri Have you been able to resolve this? If not, can you describe the steps you are following and any errors you receive?

**Comment by adrienthebo** [comment]
This issue hasn't seen an update in several months, and it looks like this is an issue installing r10k via bundler/rubygems. R10k is packaged as a standard gem, so I suspect you'll have an issue installing any gem.

Because this is out of my hands I'm going to close this issue; if you're able to track this down to an issue inside of r10k please comment on this issue and I can reopen it.
