### ISSUE TITLE
Optionally have r10k warn if a newer forge module is available

### ISSUE THREAD

**Issue by adamcrews** [puppetlabs/r10k#150]
A typical puppetfile will list forge modules and specific versions of the modules to install.  It would be nice to have a command line flag to produce warnings if a newer version of that forge module is available than what is specified in the puppetfile.  Perhaps 2 command line parameters are needed, one to warn if there is a newer supported module, and one to warn if there is a newer module overall.

**Comment by rnelson0** [comment]
I'd like to see a third parameter that directs r10k to install the latest version of the modules in the specified environment. Currently I have to wipe the whole thing (including cache) and re-deploy, update the Puppetfile with the 'latest' ref, or lock to specific versions. If I don't, the development environments are different than production, since the development envs get the latest version of each module and the production env has whatever version was installed back in June when I set up r10k.

I won't _always_ want it to stay latest in production, but if I can test it in a dev env, then I can do a single run to update to latest with confidence.

**Comment by HT43-bqxFqB** [comment]
This would be awesome to have, as there is no rss feed or something equivalent on forge

**Comment by tampakrap** [comment]
I have written a rake task that checks the version between my puppetfile and the forge release, and prints an OUTDATED message if so. It is very limited though, as it does not work for git cloned modules, and the version of each module needs to be explicitly specified in the Puppetfile. Feel free to take a look, feedback welcome: https://github.com/tampakrap/r10k-rake-tasks/blob/master/lib/r10k-rake-tasks.rb

**Comment by rnelson0** [comment]
@tampakrap That seems pretty cool. Any chance you would upload that to rubygems so others could use it in their Gemfiles?

**Comment by raphink** [comment]
https://github.com/camptocamp/puppetfile-updater also provides a rake task which checks for newer versions of modules on the forge or github.

It also automatically updates the Puppetfile.

**Comment by tampakrap** [comment]
meanwhile I publised mine as requested https://rubygems.org/gems/ra10ke
