### ISSUE TITLE
[logging] INFO goes to stderr

### ISSUE THREAD

**Issue by globin** [puppetlabs/r10k#153]
Currently INFO log messages are outputted to stderr instead of stdout.

**Comment by adrienthebo** [comment]
All log messages currently go to stderr, per https://github.com/adrienthebo/r10k/blob/master/lib/r10k/logging.rb#L66 . I've filed an issue detailing the need for a logger that outputs all informational messages to stdout and all warnings and errors to stderr in GH-148. Because this issue is subsumed by GH-148 I'm closing this issue in favor of the existing issue.
