### ISSUE TITLE
read on stderr hanging for git ssh operations with ControlPersist

### ISSUE THREAD

**Issue by jeremy-asher** [puppetlabs/r10k#169]
When using ssh with ControlMaster/ControlPersist, while the ssh client double forks to open the master process, the new child retains the old stderr fd.  This causes r10k to hang on git commands that use ssh here:
https://github.com/adrienthebo/r10k/blob/master/lib/r10k/util/subprocess/posix/runner.rb#L42

The stderr read hangs until the ssh master session is killed or the timeout is reached if ControlPersist is set to a number.  This obviously defeats any benefit to using this optimization.  I have re-opened a bug with openssh about this behavior:
https://bugzilla.mindrot.org/show_bug.cgi?id=1988

For the time being, I have worked around the issue by using the GIT_SSH environment variable pointing to a ssh wrapper script that does a 2>/dev/null.  This is extremely clunky, but bypasses the issue.

I'm not sure if there is anything that can be done on the r10k subprocess management side that isn't a huge hack, but I thought it was worth logging this issue anyway.

**Comment by adrienthebo** [comment]
@jeremyasher by closing stderr do we risk losing any log information from Git?

**Comment by jeremy-asher** [comment]
It looks like r10k is parsing the stderr output in some cases, so I don't think it could be universally ignored.  Since the process is supposed to have exited by the time stderr is read, I was thinking it might be possible to avoid the blocking read on stderr_r by manipulating it first or using a different read command.

**Comment by adrienthebo** [comment]
If you use the `GIT_SSH` environment to reopen stderr does that break the ability of r10k to parse error messages?

**Comment by jeremy-asher** [comment]
From what I've seen, this doesn't seem to affect Git's error messages, so it shouldn't affect r10k.  I am guessing Git isn't really using stderr from ssh, but I haven't really checked.  I've been thinking about how this could be solved in r10k and will send in a PR shortly.

**Comment by adrienthebo** [comment]
This might not be a supportable use case because of the intersection of https://github.com/puppetlabs/r10k/issues/265 and https://tickets.puppetlabs.com/browse/RK-18 ; we can't wait till the command completes to read stdout/stderr because that could cause the process to block, and the only way we know that we've read all of the output is by reading to EOF. I'll try to make sure this use case still works but it might not be possible to do this safely without doing something like throwing in a `sleep` or something else equally unpleasant.

**Comment by jeremy-asher** [comment]
Hopefully this can keep working without any more ugly workarounds.  I'll take a look at the new code around this to catch up.

**Comment by adrienthebo** [comment]
It might be possible to allow certain commands to preemptively close stderr. However it's extremely hard to work around file descriptors not reaching EOF when the process has closed, as you don't know how long you need to wait to read all available output. This isn't going to ship for a while so there's no risk of breaking, but since this could be a possible regression I wanted to make this known sooner rather than later.

**Comment by jeremy-asher** [comment]
Okay, I caught up on the changes since to the subprocess classes.

(Edit: moving my comments to the open PR)

**Comment by adrienthebo** [comment]
(For my own documentation)

This also affects [pssh](https://code.google.com/p/parallel-ssh/issues/detail?id=67) and [gbp-pull](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=708296), and was rejected as a bug by [python subprocess](http://bugs.python.org/issue4216).
