### ISSUE TITLE
r10k puppetfile utility has no option to *not purge existing modules

### ISSUE THREAD

**Issue by malnick** [puppetlabs/r10k#172]
Add an option to the r10k puppetfile utility to not purge. By default it purges all modules in the directory you specify or in the local ./modules directory which it is ran. There is no option to not purge, which would be useful.

**Comment by adrienthebo** [comment]
The main use  case that I know of for this is to work around GH-92, are there other concrete use cases for this?

**Comment by kian** [comment]
We have modules checked into the "modules" directory, which r10k manages.  I also specify a few external modules in Puppetfile which r10k pulls from GitHub.  When deploying a dynamic environment, I want the "modules" directory to contain both Puppetfile-defined modules, and the modules that were already checked in.

This feature would help me there.

I'm aware of workarounds however:
- create a separate repo for each module and add to Puppetfile (move out of Git)
- Use a different directory (site vs. dist) for modules from Puppetfile vs modules inside repo, and include both in modulepath

Also, thanks for this amazing piece of software.

**Comment by kian** [comment]
I retract my comment about this feature being helpful for us.

I ended up using two separate directories -- one for r10k-managed modules, another for modules added directly to the repo.

This seems to be a cleaner approach.  No longer need support for this feature.  Thanks again for r10k!

**Comment by adrienthebo** [comment]
@malnick since GH-92 has been resolved do you still need this functionality?

**Comment by nguillaumin** [comment]
That would be quite useful for me. I'm willing to use r10k, but most of my modules are still in a big SVN checkout under `/etc/puppet/environments/production/modules/`. I started to move some of them to individual Git repositories, but I'm not ready to move all of them yet.

Currently I can't use r10k because it will purge all those "unmanaged" modules. So either a "nopurge" option, or the ability to specify local modules to ignore in the `Puppetfile` would be helpful.

**Comment by arnoudj** [comment]
Being able to specify a module as local would be very useful for me too.

**Comment by kshcherban** [comment]
+1 for option to not purge at all or to exclude specific files/directories from removal.

**Comment by binarypod** [comment]
Like many users that have already commented on this, it would be of great benefit to be able to configure r10k to _not_ automatically purge at all, or only purge a specified set of files/directories.

**Comment by adrienthebo** [comment]
Right now r10k will purge the moduledir, but you can have r10k install modules from the Puppetfile into a secondary directory (https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#moduledir) so that your modules directory will not be modified; this can be used as a workaround until I can properly address this.

**Comment by adrienthebo** [comment]
There are now two issues in JIRA for this - [RK-149](https://tickets.puppetlabs.com/browse/RK-159) which tracks the `local` module type which is a short term fix, and [RK-159](https://tickets.puppetlabs.com/browse/RK-159) which tracks the long term fix of not purging modules created by Git (or SVN).

At this point, I would like to just talk about the behavior of `r10k puppetfile install` - Given that GH-92 was fixed, is there a use case for having something like `r10k puppetfile install --no-purge` ? If you're installing modules out of a Puppetfile into a local directory, what are the circumstances that you would have contents in the Puppetfile managed directory that r10k did not place there?

**Comment by jyaworski** [comment]
@adrienthebo that's exactly what I would want from this. A --no-purge option would be great.
