### ISSUE TITLE
Deploying a single environment also runs purging

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#213]
With the revamped deploy logic, running `r10k deploy environment -p envname` purges all environments before deploying the given environment(s). This doesn't seem like desirable behavior to default to; more fine grained handling of purging needs to be worked out.

**Comment by adrienthebo** [comment]
Note: This only affects the r10k master branch, and has not been released.

Strictly speaking this is not new behavior; earlier versions of r10k would deploy the given environment and then purge stale environments. The refactoring of the deployment code just puts this issue more in the forefront.

**Comment by jeffmccune** [comment]
Hi @adrienthebo, I'm working on site at a customer doing a pretty heavy upgrade from PE 3.1 all the way to PE 2016.4.3.  They have a rather unique module layout, but it's not that strange.  I'm trying to come up with some changes to their single `modules` repository (which contains all of their Puppet code) that makes it look a lot like a control repository.  The Puppetfile will deploy the only other repository they have, which is hieradata.

They have 6 environments, none of them are named `production`.  I'm working with r10k directly as I whip everything into shape.  In PE 2016.4.3 I'm observing that r10k keeps purging the `production` environment presumably because this customer doesn't have a git branch named `production`.  Is there any way to disable this purging behavior while I focus on a single environment and Git branch while I get things into shape?  I looked through the docs, the config file, the interactive help but didn't see anything.  Looking through the code, the only thing I see is the mention of an exclusion list in the Purgeable class, but I'm not sure if that's intended to be end user configurable or not.

Hope all is well, apologies for summoning an ancient issue from the depths.

**Comment by jeffmccune** [comment]
Here's what I'm observing and looking for a way to work-around.  My goal is to exercise the a topic branch while I get the code compatible for all of PE 3.1, 3.8 and 2016.4.3

```
[root@acme.com environments]# ln -s jeff_pe2016_config production
[root@acme.com environments]# ls -l
total 4
drwxr-xr-x 9 root root 4096 Apr  4 15:44 jeff_pe2016_config
lrwxrwxrwx 1 root root   18 Apr  4 16:05 production -> jeff_pe2016_config
[root@acme.com environments]# r10k deploy environment jeff_pe2016_config -v
INFO     -> Deploying environment /etc/puppetlabs/code/environments/jeff_pe2016_config
INFO     -> Environment jeff_pe2016_config is now at b1b49e333d2ea1394a0d13ff524ff18bda4bd27b
INFO     -> Removing unmanaged path /etc/puppetlabs/code/environments/production
```
