### ISSUE TITLE
Make modules dir overridable

### ISSUE THREAD

**Issue by igalic** [puppetlabs/r10k#24]
Right now, r10k's very opinionated configuration management is not overridable. If we want to create more complex structures of modules such proposed here: http://somethingsinistral.net/blog/configuration-management-as-legos/

In our environment we'd like to do something like that, however a configuration of:

```
:cachedir: '/var/cache/r10k'
:sources:
  :modules:
    remote: 'git@my-org/puppet-modules'
    basedir: '/etc/puppet/modules'
  :site:
    remote: 'git@my-org/puppet-site'
    basedir: '/etc/puppet/site'
  :projects: 'git@my-org/puppet-projects'
    basedir: '/etc/puppet/projects'

:purgedirs:
  - '/etc/puppet/modules'
  - '/etc/puppet/site'
  - '/etc/puppet/projects'
```

will create a very nested directory structure. It would be nice if it r10k simply cloned the envs into: `/etc/puppet/modules/$environments` instead of creating `/etc/puppet/modules/modules/$environments` -- say, with a switch for "shallow: true", or alternatively, if we could tell it to put the sites into "/etc/puppet/$environment/sites". (although I wouldn't know what kind of configuration scheme to use here)

We are aware that this would break full compatibility with librarian-puppet. This is something that r10k users would have to opt into.

**Comment by csschwe** [comment]
I think this would be very useful  +1

**Comment by larstobi** [comment]
+1

**Comment by adrienthebo** [comment]
@igalic @csschwe @larstobi would #35 be sufficient for this use case?

**Comment by igalic** [comment]
here's a test: https://gist.github.com/igalic/5767142 = wonder what I'm doing wrong here. Other than the fact that most of my modules are probably lacking their appropriate branches? But then why are the forge modules not installed either?

**Comment by Ancillas** [comment]
Are you passing the -p flag to r10k when you run it?

**Comment by abohne** [comment]
+1 on this.  I am using `/etc/puppet/modules/$environments` and all my branches (development, production, etc) reside under that directory.

So I want to end up with something like this:
`/etc/puppet/modules/development/stdlib`

With `stdlib` being defined as in `Puppetfile`.

#35 seems to get half-way there, but it doesn't quite solve the issue.

**Comment by adrienthebo** [comment]
@abohne for clarification, you want all Puppetfile deployed modules at the root of the environment?

**Comment by adrienthebo** [comment]
This issue has been open for a while but I admit I'm not entirely clear on what the desired solution is. I see two different solutions here - one is that r10k should allow Puppetfiles to install modules into different module directories like so:

``` ruby
moduledir 'site' do
  # site modules
end

moduledir 'forge' do
  # forge sourced modules
end

moduledir 'git' do
  # git sourced modules
end
```

Given the above example, each moduledir group would be installed into a separate module directory to provide logical separation.

The other solution is that an r10k source repo will only contain a Puppetfile, and when installing modules it will put them into the root of the module. Does this sound correct?

**Comment by adrienthebo** [comment]
As part of the changes that were made for directory environments, the assumption is now made that modules will live in [`$environmentpath/$environment/modules`](https://docs.puppetlabs.com/puppet/latest/reference/config_file_environment.html#modulepath). Changing this to be the top level environment would be very difficult, especially when you take into account how files like `environment.conf` and `Puppetfile` should be handled with respect to purging.

If anyone desperately wants this feature I can leave this open, but if not I'll close it out in a week or two.

In addition, GH-141 allowed the `moduledir` setting to be relative so that a custom Puppetfile modules directory could be set, and GH-133 will add support for multiple moduledirs if desired, so those issues may also provide for the needs laid out here.

**Comment by igalic** [comment]
from my pov, this can be closed, not sure about the other people ~impacted~ by this.

**Comment by adrienthebo** [comment]
Since there hasn't been more discussion over why this is needed over the functionality provided in GH-141 for alternately named module directories, and directory environments assume that modules are not at the top level of an environment path and make this harder to use, I'm going to close this issue. If this issue is not actually resolved please comment on it and I can reopen it. Thanks!
