### ISSUE TITLE
Add support for installing module dependencies

### ISSUE THREAD

**Issue by larstobi** [puppetlabs/r10k#38]
When using r10k, it will install modules from the forge using the flag "--ignore-dependencies". Using git modules, dependencies are not installed either.

I have to manually track down dependencies, using grep on Modulefiles and adding them to the Puppetfile. I think it would be useful to have r10k resolve dependencies and install them also. What do you think?

**Comment by adrienthebo** [comment]
+100 for this feature. Definitely.

However, dependency resolution is a bit tricky, so this won't be coming right away, but this is a must-have feature.

**Comment by larstobi** [comment]
After talking to a buddy this Tuesday, it is clear that not everybody wants this, so it should be optional.

**Comment by adrienthebo** [comment]
If nothing else, I want this feature. :)

I actually talked with a few people who were thinking of implementing an independent dependency and versioning library. I don't know all the details and it could amount to vaporware, but if that picks up steam then it could be directly added in and r10k could get dependency resolution for free.

**Comment by larstobi** [comment]
Sounds good.

**Comment by ekohl** [comment]
I know https://github.com/openSUSE/libsolv aims to be a nice library for resolving dependencies, but I have no idea how usable it is for puppet modules. I do know I'd like something like this :).

**Comment by eliasp** [comment]
@ekohl libsolv seems to be a relatively heavy-weight package considered module dependencies aren't that complicated.
It is written in C and requires CMake for building it, which would mean the r10k installation process would be way more complicated then.

Making use of usually already existing and Ruby-only solutions (gem, Bundler) for dependency resolution might make more sense.

**Comment by ekohl** [comment]
@eliasp that certainly makes sense.

**Comment by kitchen** [comment]
also, supporting librarian-puppet's Puppetfile.lock would be awesome.

**Comment by justenwalker** [comment]
IIRC, the version scheme for the Puppet Module Forge is semver 1 or 2 - which is not compatible with gem/bundler versions -- so another version abstraction might be necessary.

I encountered this problem on librarian-puppet and ended up writing a semver parser. Perhaps there is a better library out there to take care of this; but if not, maybe this will help: [semantic_version.rb](https://github.com/justenwalker/librarian/blob/34d47dddf0a5119247b7a12aa9e6c36591565492/lib/librarian/manifest_version/semantic_version.rb).

**Comment by adrienthebo** [comment]
@kitchen I've been doing some research and it looks like implementing a Puppetfile.lock will be a necessity to make  dependency resolution performant. I still have to nail down the exact details in how to balance ease of updates with dependency resolution, but Puppetfile.lock is in the cards.

Unfortunately it looks like the only standalone dependency resolution tool that's currently available is [solve](https://github.com/RiotGames/solve), which is an _offline_ dependency resolution tool. That is, you have to have all the versions of all your libraries available up front, which isn't really an option for a tool like r10k.

One option could be to extract the existing dependency resolution from librarian, so that we can get online dependency resolution without having to bring in the entire librarian project.

**Comment by beddari** [comment]
Just to put it out there, for the future I'd love to have dependencies done in a better and more flexible way, like e.g similar to how npm does it, https://npmjs.org/doc/json.html#dependencies

I heard that Modulefile is going away at some point(?) to be replaced with a simple metadata.json - that could very well be an opportunity for PL to open up the 'standard' deps format (allow git refs!!)

**Comment by beddari** [comment]
Someone beat me to it : https://projects.puppetlabs.com/issues/22098

**Comment by adrienthebo** [comment]
As an update to anyone watching this, I have some preliminary work on the core for dependency resolution, so there is forward movement on this.

**Comment by njam** [comment]
Some [quotes from the puppet-users group](https://groups.google.com/forum/#!msg/puppet-users/6PxwrXtuPGo/r2lGBWaQE1kJ) regarding the `Modulefile` -> `metadata.json` transition:

> metadata.json (part of the `puppet module build` output) will become the single-source of metadata
> 
> The next major version of Puppet will include a greatly revamped Puppet Module Tool that (amongst other improvements) will make it easy to express and validate the new metadata directly in metadata.json.

There's a [gem to interact with `metadata.json`](http://ruby-doc.org/gems/docs/p/puppet-module-0.3.3/Puppet/Module/Tool/Metadata.html).

To me it seems the sanest would be to support `metadata.json` with custom fields for non-forge sources, e.g.:

``` json
{
    "name": "puppetlabs/mysql",
    "version": "2.1.0",
    [...]
    "dependencies": [
        {
            "name": "foo/bar",
            "version_requirement": ">= 2.2.1",
            "source": "git@github.com/foo/bar.git" <--ADDED
        }
    ]
}
```

And maybe also allow this kind of declaration for environments instead of using a `Puppetfile`?

**Comment by amateo** [comment]
As puppet module install resolves dependencies, is there any option to run it from r10k without the --ignore-dependencies flag? I think it could be an easy solution at least for this kind of modules.

**Comment by AnneTheAgile** [comment]
fyi, puppet ticket was moved to; https://tickets.puppetlabs.com/browse/PUP-1181
[PUP-1181] Modulefile dependency should support git repo as source - Puppet Labs Tickets

**Comment by feniix** [comment]
This would be a dreamed feature

**Comment by gehel** [comment]
Would love to have this feature as well ! As a Java developer, I am used to dependency management in Maven, and I think a lot can be learn by looking at how it works. Java might not be the most popular technology in the Puppet realm, but please let that aside for a moment. Dependency management is hard. Thought need to go in to things like version ranges, conflict resolution, overriding, optional dependencies, analysis tools, indirect dependencies, ...

I've been thinking a lot about writing a Maven plugin to manage my Puppet workflow (yes, it sounds like heresy). While that might not be everyone's favourite solution, it might start an interesting discussion that might end up in improvements in r10k. Let's see if I find some time to dig into it ...

**Comment by bastelfreak** [comment]
I wrote a ruby script which fetches modules from forge and clones it into my own git repo. It also resolves dependencies. Maybe this is useful for anyone (let me know if you need more features - I can probably implement them):
https://github.com/bastelfreak/scripts/blob/master/forge_client.rb

**Comment by txaj** [comment]
I would more see a mechanism that would resolve both dependencies set in metadata.json & Puppetfile, and warn the user on conflicts or unsupported setups

**Comment by bkc1** [comment]
+1 for adding r10k functionality to handle mod dependencies.

**Comment by gudron** [comment]
+1.
for me - r10k unusable without this feature

**Comment by adrienthebo** [comment]
First off, we're incrementally moving GitHub issues for r10k from here to JIRA (see https://tickets.puppetlabs.com/browse/RK), so I'm closing out this issue in favor of [RK-3](https://tickets.puppetlabs.com/browse/RK-3).

Since it doesn't look like I've discussed it here, I'll briefly touch on why this has been so long coming.

To begin with, yes - dependency resolution would be very nice and it's quite painful to live without it. I hate the fact that right now users have to manually unroll dependencies. If this was something that we could just stuff into r10k and go from there then I would have done it long ago.

Unfortunately it's not as simple as grabbing a dependency resolver and slapping it into r10k. As @adreyer can attest to, the current dependency resolver in Puppet is pretty flawed - right now it can give incorrect results when resolving dependencies, which significantly degrades the usefulness of dependency resolution. In addition when a set of dependencies can't be installed together (two different modules require incompatible versions of a third module) it can take a long time for resolution to fail, and when it does you're given absolutely no information to figure out what went wrong and why. Lastly, the API of the current resolver in Puppet is in pretty poor shape, and integrating it into r10k would be enough hurt that it makes more sense to fix up the resolver before bringing it in to r10k.

I'm not as familiar with the librarian-puppet resolver as I am the Puppet resolver, but my understanding is that it suffers from similar problems.

In addition, adding dependency resolution to r10k in general is challenging. The expected approach of resolving dependencies when r10k runs on a Puppetfile, coupled with the fact that r10k is frequently run via a webhook or some remote method means that if dependency resolution fails it's hard to even see if r10k ran into issues while resolving dependencies.  In addition r10k supports tracking Git branches for Puppet modules; this approach of continuously updating a package in this manner doesn't mesh well with dependency resolution.

All of these problems are solvable problems (aside from dependency resolution being NP complete; we're pretty hosed on that front.) However, it takes time and effort to solve these problems, and the the core developers on r10k have limited resources - there's only so many hours in a day and we have to determine which tickets provide the most amount of value to the most amount of users. This is a painful process and it does mean that we do have to let some issues slip, but trust me - this is on our radar, we want to solve it, and we _will_ get to it as soon as we can.

In the mean time, if r10k doesn't meet your needs, then I am sorry - and I hope that you can find a tool that meets your needs. We do the best we can on r10k and we're trying to make the lives of our users easier, but if there's something better out there then please - by all means use what works best for you.

So again, sorry for the delay in getting this resolved, and thanks for your patience!

**Comment by adrienthebo** [comment]
Closing in favor of [RK-3](https://tickets.puppetlabs.com/browse/RK-3).

**Comment by ravitri** [comment]
Hello,

Anyone aware of using source as a *.tar.gz from a HTTP server in metadata.json or Puppetfile ? 

Something like :

"dependencies": [
        {
            "name": "foo/bar",
            "version_requirement": ">= 2.2.1",
*\*            "source": "http://x.x.x.x/modules/abc.tar.gz" **
        }

Is this possible ?
