### ISSUE TITLE
Missing explicit error message for non-existing remote

### ISSUE THREAD

**Issue by eliasp** [puppetlabs/r10k#46]
When a defined remote doesn't exist, the thrown error message is not really helpful:

**r10k.yaml**

```
:sources:
    :mysource:
        remote: '/some/non/existing/directory.git'
        basedir: '/etc/puppet/environments'
```

`r10k deploy environment` runs into this error message:

```
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Deployment::DeployEnvironments:0x00000001efaa00> failed while running: "git clone --mirror /some/non/existing/directory.git/ /var/cache/r10k/-some-non-existing-directory.git" returned with non-zero exit value 128
```

I don't know whether there's a straightforward way to handle this more gracefully, but the current error message is not really helpful either.

**Comment by adrienthebo** [comment]
Targeting at `1.1.0`.

**Comment by adrienthebo** [comment]
Right now I would have to parse the output of `git clone`, and while that works it's not the most elegant solution. I'm looking into using https://github.com/schacon/ruby-git for interacting with git but it doesn't support git object alternatives. I've filed https://github.com/schacon/ruby-git/issues/94 and if the issue is accepted I can pull in that library and hopefully resolve this.

Since this could take a little while to get resolved, between changing ruby-git and pulling it into r10k I may not be able to get this in 1.1.0. I'm going to remove the milestone for now; if we get a really quick turnaround on upstream then I'll re-add this to 1.1.0.

**Comment by adrienthebo** [comment]
See also GH-96.

**Comment by adrienthebo** [comment]
Fixed as part of GH-96:

```
└> bexec r10k deploy environment   
[R10K::Util::Attempt - ERROR] Couldn't update git cache for /some/non/existing/directory.git
Original exception:
Command exited with non-zero exit code:
Command: git clone --mirror /some/non/existing/directory.git /home/adrien/.r10k/git/-some-non-existing-directory.git
Stderr:
fatal: repository '/some/non/existing/directory.git' does not exist
Exit code: 128
```
