### ISSUE TITLE
new tags are not deployed when i deploy environment 

### ISSUE THREAD

**Issue by iakovgan** [puppetlabs/r10k#485]
Context: r10k=1.2.1

Given: i push a new tag to a module repo
     and i change Puppetfile to use this new tag 
 when i run "r10k deploy environment ENV -vp", 
then r10k fails to deploy the tag with UnresolvableRefError

When i deploy module 'r10k module deploy MODULE -v', 
then the error disappears and deploy environment works as expected.

**Comment by adrienthebo** [comment]
First off, r10k 1.2.1 is over a year old and there have been a lot of improvements made since then, especially to logging, error handling, and Git module and environment handling in general. If you are able to update r10k to a more recent version, could you do that? Barring that, could you reproduce this issue and run `r10k --verbose debug2 <your command>` to produce logs of what's going on, and attach those logs?

**Comment by adrienthebo** [comment]
It's been about a week since this issue has seen an update, does this issue still affect you?

**Comment by iakovgan** [comment]
Sorry spend some time trying to install the latest version and finally rolled back to the working one (update of ruby broke some things). 

Eventually I've added a gitlab hook on tagging so that hook runs `r10k deply module MODULE -pv` on every tag operation (same hook as on push actually). 
This actually solves my issue. 

Thanks.
