### ISSUE TITLE
Purging all environments when specifying more than one 

### ISSUE THREAD

**Issue by lutaylor** [puppetlabs/r10k#52]
We are currently having the following problem.

If we specify more than one git repo in our yaml file it will purge out the directories right after deploying them.

e.g.
...
    [R10K::Task::Module::Sync - INFO] Deploying fedora into /etc/puppet/environments/metro/modules
    [R10K::Task::Module::Sync - INFO] Deploying stackbase into /etc/puppet/environments/metro/modules
    [R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /etc/puppet/environments
    [R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /etc/puppet/environments

Here is our yaml file

```
# The location to use for storing cached Git repos
:cachedir: '/var/cache/r10k'

# A list of git repositories to create
:sources:
 :metro:
   remote: 'git@github.com:discoverygardenpuppet/env_metro.git'
   basedir: '/etc/puppet/environments'
 :env_ir:
   remote: 'git@github.com:discoverygardenpuppet/env_ir.git'
   basedir: '/etc/puppet/environments'

:purgedirs:
  - '/etc/puppet/environments'
```

If we comment out either one and rerun it deploys fine and doesn't delete them after. I have tried deleting the /var/cache/r10k as well and it has no impact.

**Comment by Ancillas** [comment]
I created a small workaround for this last week in my environment, but it's not good enough to be considered a patch.

https://gist.github.com/Ancillas/6135084

Line 72 is what I commented out to stop r10k from purging.

**Comment by adam-vessey** [comment]
Been looking into this a bit... Looks like it's because both use the same "basedir", and so detect each others directories as being "stale"... So when the first purges it's stale stuff, it deletes those of the second, and then the second deletes those of the first. This seem to come out of a bad assumption made in https://github.com/adrienthebo/r10k/blob/master/lib/r10k/util/purgeable.rb#L21-L28, where assumes each "managed directory" is only used by a single source. 

... I'm thinking that it may be necessary to:
1. list the contents of each managed directory (in a hash of arrays?), 
2. iterate over each source and remove the "desired" contents from our listing
3. delete all entries remaining in the listing from the filesystem

Poking around the code (and being new to Ruby), I'm not sure where would be the place to make this change... Alternatively, could make the created environments be prefixed with the name used in yaml? So in the example above, we might end up metro_dev, metro_test, env_ir_dev and env_ir_test...  Seems like this alternative might address #48 as well.

...  I may take a shot at this...

**Comment by adam-vessey** [comment]
...  Which is to say, that I have. :P

https://github.com/adrienthebo/r10k/pull/53 allows prefixes to be used... Would pretty much have to be used in the case that multiple sources are in use. This should satisfy #48.

**Comment by Ancillas** [comment]
What does the file system look like if prefixes are used?

Greg

**Comment by lutaylor** [comment]
This has been addressed by Adam's fix.
