### ISSUE TITLE
Ignore PAX files

### ISSUE THREAD

**Issue by rnelson0** [puppetlabs/r10k#558]
When installing a module compiled with PaxHeaders, you receive errors from minitar as it cannot read the PAX Headers. See [gnupg #18](https://github.com/n1tr0g/golja-gnupg/issues/18) for an example. This was fixed in Puppet in [PR2872](https://github.com/puppetlabs/puppet/pull/2872).

**Comment by scotje** [comment]
Seems like we should be able to implement the same fix as in the PMT PR, might actually land in forge-ruby though, I'll take a look.

**Comment by scotje** [comment]
So, it looks like the skipping logic already exists in the puppet_forge gem that recent versions of r10k use. The files skipped due to PaxHeaders are logged at WARN but it doesn't actually impact the r10k run. Is the issue that you think the logging should happen at a lower level than WARN by default?

**Comment by rnelson0** [comment]
Yes, it's a warning from tar, but not a warning for r10k as that's expected behavior. In PR2872, it was logged as debug and I think that is sufficient.

**Comment by scotje** [comment]
👍  I'll get a PR up to lower the message to DEBUG

**Comment by rnelson0** [comment]
Thanks! Is that targetted at a specific release version for r10k?

**Comment by scotje** [comment]
Not yet, but there should be a new r10k release that contains it this week.

**Comment by scotje** [comment]
r10k 2.3.0, which includes this fix, was released today.

**Comment by rnelson0** [comment]
Awesome, thank you!
