### ISSUE TITLE
allow modules from stable environment to be symlinks in other environments

### ISSUE THREAD

**Issue by Poil** [puppetlabs/r10k#562]
Hi,

It'll be nice to allow to configure a stable environment name, when we create a new branch on a module, all modules that are not in this branch, will be symlinks to the "stable environment".
We'll be able to win some freespace and to keep the features environment up to date.

**Comment by scotje** [comment]
There has been some discussion about adding a way for modules to track a branch matching the name of the environment they are included in, and then having a default for when there isn't a match.

However, this would probably not involve symlinks due to the portability issues they present between platforms.

**Comment by Poil** [comment]
All Unix like and Windows since Vista support symlinks :)

**Comment by luisfdez** [comment]
Maybe it would be easier to define a kind of 'hierarchy' where your environment can inherit from another one and you just override the modules you want to work on.

This reminds me the functionality available in git-repo where your manifests can extend other manifests overriding the references.

Independently of the way it's implemented, having such functionality in r10k is a must. It would make some everyday tasks easier.

@scotje , is there any ticket at Puppet Labs tracking this?

**Comment by scotje** [comment]
@Poil Until we drop support for Ruby 1.9.x we would have to write an entirely standalone symlink implementation for win32. Even many of the 2.x versions of Ruby had issues with symlinks on win32. I'm not saying it's impossible, just unlikely that we will pursue that approach.

Generally, I think it's unwise to introduce cross-environment inter-dependencies at anything more than a logical level. E.g. you can say that the `dev_one` environment logically inherits modules from `production` but `dev_one` would still have it's own copy of everything on disk. Maybe other people disagree, but it seems like it would introduce at lot of potentially weird side effects from deployments in order to save a relatively small amount of disk space.

@luisfdez I created https://tickets.puppetlabs.com/browse/RK-211 to track the idea of environment inheritance broadly.
