### ISSUE TITLE
Add SVN puppet module provider.

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#58]
Use cases TBD

**Comment by vjanelle** [comment]
Git provides various layout options, which may be useful as a transition device.

I'm thinking mostly of situations where people have checked their entire puppet repos into SVN, and you end up with situations like

branches/${branchname}/.../modules/${modulename}
trunk/.../modules/${modulename}

etc - Selecting which branch vs trunk is done on a different level.

SVN doesn't really care about this, since it has no concepts of branches, tags, etc.  SVN clients implement this because they can track through the revision graph.

**Comment by igalic** [comment]
I think we could extend this from Subversion to: $SCM. Right now I'm trying to fight many puppet and ruby related tools to fit a module that lives outside of the Git Monoculture. r10k being one of those tools.

**Comment by adrienthebo** [comment]
Preliminary module support has been merged in next in 2492180. It would be a tremendous help if people could play around with installing modules from SVN and find holes in the implementation.

**Comment by adrienthebo** [comment]
This has been released in 1.2.0; I'm going to create a new issue for dynamic environments (ish) based on SVN.
