### ISSUE TITLE
Allow Limited Variables or Substitution in the PuppetFile

### ISSUE THREAD

**Issue by bgshacklett** [puppetlabs/r10k#595]
I would like to be able to deploy different versions of modules to matching environments. For instance, deploying the 'develop' branch of a module when deploying the 'develop' environment. It seems that some limited variable support might be a good way to make this happen. For example:

```
mod 'role_profile',
  :git    => 'https://gitlab.localdomain.com/devops/puppet-roleprofile',
  :branch => '${environment}'
```

Given the above configuration in the Puppetfile, R10k would pull the branch which matches the environment currently being deployed. E.g. if R10k was pulling the 'develop' environment, it would pull the 'develop' branch of the `puppet-roleprofile` module.

This would enable an easier workflow for developing modules, while still allowing changes to the Puppetfile to be tracked with a Git-Flow type workflow from development to production.

**Comment by scotje** [comment]
We've actually got some tickets planned around this exact workflow already:

https://tickets.puppetlabs.com/browse/RK-223
https://tickets.puppetlabs.com/browse/RK-235

We have something of a longer term goal of making the Puppetfile more portable (e.g. machine readable without a full Ruby interpreter) which is why we're looking at a new option/keyword approach rather than something like variable substitution. (https://tickets.puppetlabs.com/browse/RK-212)

Thanks for your feedback and feel free to post any comments you would like on those tickets.

**Comment by bgshacklett** [comment]
Much appreciated scotje. It looks like RK-235 is almost exactly what I'm looking for.
