### ISSUE TITLE
r10k and applications tiers

### ISSUE THREAD

**Issue by fonk** [puppetlabs/r10k#607]
Hi!

Maybe this topic would better fit on the mailing list, but unfortunately users without google account are locked out...

We implemented the concept of application tiers and puppet environments mentioned here: http://garylarizza.com/blog/2014/03/26/random-r10k-workflow-ideas/ and it works great for us so far. But we're now hitting the following problem and I'd like to know if there's a solution that's better supported by r10k or if we're doing things wrong.

We have one or sometimes two puppet environments: env_prod and maybe env_test, which mainly just include the Puppetfile (and thus the modules) and are used for testing puppet dsl code. We check them out using "r10k deploy environment env_prod -p" and everything's fine.
Our application tiers are called dev, test and prod. We've multiple teams committing hiera-code in different repositories, for example team A supplys hiera-config for App1 and App2 via repo "TeamA" and team B supplys hiera-config for App3 via repo "TeamB". At the moment every team repo has the branches dev, test and prod.

The problem is, that we'd like to deploy the hiera-code for the Apps independently. If we now run "r10k deploy environment dev", the checked-in code for all three applications gets checked out. We tried to rename the branches like app1_dev, app2_dev, app3_dev, but are not quite happy with that (mainly because changes to apps of the same team are often the same and can't be done in one commit if they're in different branches, which makes reviews more complicated...).
Is there any (planned) way to tell r10k to just checkout a branch of one named repository? Is r10k the wrong tool for checking out hiera-configs? I'm curious what you think about it...

Best regards,
Frank

**Comment by scotje** [comment]
There are actually a couple of improvements we are working on right now to make managing Hiera data with r10k simpler. The first improvement, which is already merged into master here, is letting you install individual items from the Puppetfile into alternate paths inside the environment: https://tickets.puppetlabs.com/browse/RK-222

Another related improvement is adding a way to install Git content from a branch name that matches the control repo branch name: https://tickets.puppetlabs.com/browse/RK-223

The overall goal is to let you just manage Hiera data from inside the Puppetfile of a single source instead of relying on multiple sources. Does that sound like it would be helpful to your workflow?

**Comment by fonk** [comment]
Hi! Thanks for you answer, but both mentioned features seem to bind the hiera data more to the control repo, i.e. the puppet environment. IMHO that's the opposite of what gary said in his blog post.

We need a way to check out multiple repos that supply hiera data with more control. At the moment it seems that the only way to control which repo get's checked out is to use different branch names in every repo.
