### ISSUE TITLE
r10k subcommand change: r10k deploy display

### ISSUE THREAD

**Issue by jrodriguezjr** [puppetlabs/r10k#68]
Per our chat conv.  Possible to change " r10k deploy display" to " r10k deploy list"? I think the command flows alot better.

**Comment by adrienthebo** [comment]
If you want to implement an alias I think we could add that in, but I don't think that the command naming violates the principle of least astonishment (at least too much). We can't outright rename the subcommand because of semver, so this would have to happen for 2.0 to do a full rename.

I don't plan on working on this myself but if someone else wants to take this issue on I would be willing to consider merging this. I'll leave this open for a month or two, and if nobody comments on it I'm going to close it out for lack of interest.

**Comment by adrienthebo** [comment]
Fixed in e628642.
