### ISSUE TITLE
not able to fetch module from remote module repository which has context path in url

### ISSUE THREAD

**Issue by jainishshah17** [puppetlabs/r10k#685]
I have pointed remote module repo which proxy Forge in r10k.yaml file.
`forge.baseUrl : 'http://localhost:8080/artifactory/api/puppet/puppet-loacl' `

when I do `r10k puppetfile install` its ignoring context path while looking for module in remote module repository.

please add support to use full URL with context path for remote module repository.

which should support same behaviour like: https://github.com/puppetlabs/puppet/pull/5190

**Comment by scotje** [comment]
This issue turned out to be a bug in the `puppet_forge` gem. (https://github.com/puppetlabs/forge-ruby/pull/41) I've fixed the bug and released a new version of `puppet_forge` (2.2.3) which resolves the issue. Since `puppet_forge` is a dependency of `r10k` you should be able to run `gem update puppet_forge` to get the latest version and `r10k` should pick it up. If you are using `bundler` or some other gem management software, you may have to do something else to get the gem updated correctly.
