### ISSUE TITLE
GIT LFS support

### ISSUE THREAD

**Issue by jkroepke** [puppetlabs/r10k#695]
Hi!

it's possible to add git lfs support, even to the git rugged provider?

**Comment by logicminds** [comment]
I think this would get people in a lot of trouble.  it is only a matter of time before someone attaches a 10GB file and brings down the puppetmaster.

**Comment by jkroepke** [comment]
By design, we want to commit every 2k binary file to the git lfs layer. Let the user choose, if its doen't in puppet or it does.

**Comment by nmaludy** [comment]
+1 for this.

Git-LFS works just fine for us when using the default git provider. When using the `rugged` provider the git-lfs repos just contain file pointers and a manual `git lfs pull` has to be executed post-deploy.

Because the `rugged` provider doesnt' work, we've had to resort to a `~/.ssh/config` setup that in order for `r10k` to use the correct SSH keys when pulling from our git repos.

**Comment by pillarsdotnet** [comment]
At the very least, there should be clear documentation as to the current status of LFS support within Puppet, R10K, and Code-Manager.
