### ISSUE TITLE
Error installing puppetfile: minitar dependency issue.

### ISSUE THREAD

**Issue by lngarrett** [puppetlabs/r10k#699]
minitar released `0.6` today and installs immediately began failing:

```
r10k puppetfile install
ERROR	 -> closed gzip stream
```

Instances running minitar `0.5.4` work fine, but any new instances running minitar `0.6` are failing. Please pin minitar to `0.5.4`

**Comment by lngarrett** [comment]
https://github.com/halostatue/minitar/issues/24

This issue is actively being [worked on](https://github.com/halostatue/minitar/issues/24) so it might not stick around much longer. Still recommend pinning.

**Comment by scotje** [comment]
Yeah, we should adopt some pinning to minitar regardless of the outcome.

**Comment by scotje** [comment]
Will have a 2.5.2 gem release here momentarily that includes this pinning.

**Comment by scotje** [comment]
https://rubygems.org/gems/r10k/versions/2.5.2

**Comment by scotje** [comment]
Thanks for the report and PR @lngarrett !

**Comment by halostatue** [comment]
Note that you will want to pin to `~>0.6, >= 0.6` ASAP because 0.5 has a CVE reported against it.

**Comment by scotje** [comment]
After reading the CVE I think we might be OK because r10k doesn't do anything directly with Minitar except for a test, and the puppet_forge gem that actually uses it for extraction already verifies that the fully expanded path being extracted is within the expected unpack location. (https://github.com/puppetlabs/forge-ruby/blob/master/lib/puppet_forge/tar/mini.rb#L66-L76)

But I will look into updating the pinning tomorrow anyway.
