### ISSUE TITLE
git branch names may conflict with reserved environment names

### ISSUE THREAD

**Issue by rmnwolf** [puppetlabs/r10k#72]
https://docs.puppetlabs.com/puppet/latest/reference/environments_classic.html (was http://docs.puppetlabs.com/guides/environment.html)
says that master main agent and user are special names and may not be used for environments. r10k doesn't notice/enforce that and may cause unanticipated pain.

**Comment by adrienthebo** [comment]
So fun fact - reserved environment names actually _do_ work:

```
└> puppet32 apply --modulepath '$confdir/environments/$environment/modules' --environment master notify.pp
Notice: hi
Notice: /Stage[main]/Test/Notify[hi]/message: defined 'message' as 'hi'
Notice: Finished catalog run in 0.12 seconds
┌[adrien☮grey]-(~)
└> puppet32 --version                                                                                     
3.2.4
┌[adrien☮grey]-(~)
└> find .puppet/environments/master 
.puppet/environments/master
.puppet/environments/master/modules
.puppet/environments/master/modules/test
.puppet/environments/master/modules/test/manifests
.puppet/environments/master/modules/test/manifests/init.pp
```

**Comment by adrienthebo** [comment]
So I did not expect this at all, but apparently they do more or less work. I don't think that the code itself should check and warn about this, especially since warning on the presence of the 'master' branch could be extremely noisy. I think that this is probably best handled as documentation. What do you think?

**Comment by adrienthebo** [comment]
Per the investigation I've done this limitation was due to the behaviors of defining sections in puppet.conf and is no longer an issue with Puppet 3.6+ because of directory environments. Because this can't be solved in code and warning when a `master` environment is created would be noisy, I am going to close this out. If you think there's a better way to solve this, let me know. Thanks!
