### ISSUE TITLE
Provide a command to purge environments

### ISSUE THREAD

**Issue by rnelson0** [puppetlabs/r10k#744]
When a branch is deleted from the controlrepo, it appears the only way to purge that is to run `r10k deploy environment [$environment]`. There is no command to simply check and purge environments. In order to purge deleted environments, this could cause side effects where some external content in the deployed environment(s) is updated - for instance, a module pointing at HEAD or a branch name that has been updated since the last deploy. This could be avoided by adding a `--purge-only`, `undeploy`, or similar command to r10k.

See https://github.com/voxpupuli/puppet-r10k/issues/374 for some of the side effects of the current implementation.

**Comment by rnelson0** [comment]
This still has value for me and my current employer.

**Comment by Magisus** [comment]
We're actually actively planning to add something like this, because we're having issues in PE with running r10k in parallel to deploy environments, so some threads are purging while others are deploying, which can sometimes result in errors. See https://tickets.puppetlabs.com/browse/RK-367. If I remember right, the `deployment` level purging is what cleans up deleted envs (which is what's causing problems for us), so that work should solve this for you! I'll make sure to tag you on the PR. We're planning to start that work in the next month or so.

**Comment by rnelson0** [comment]
Is there a way to tell the bot this is in planning/development and to stop marking it stale? Other than updates like this, that is.

**Comment by mwaggett** [comment]
We ended up going in a different direction to solve the issue of parallel deployment/purging processes clobbering each other, but this still seems like it would be a helpful feature to y'all. We're working on prioritizing r10k maintenance, so we will hopefully get a chance to look into this in the not-too-distant-future.

**Comment by rnelson0** [comment]
Still need this

**Comment by prolixalias** [comment]
I'm on an OSP engagement at the moment, this would be a win for them. What we've begun rolling/testing hasn't gone well yet.

**Comment by mwaggett** [comment]
Hi @rnelson0, thanks for opening this! r10k is now considered to be feature complete and we are unfortunately discontinuing development. As a result, we are closing all open issues and pull requests. I sincerely apologize that we’re unable to address this issue.
