### ISSUE TITLE
Changelog not up-to-date

### ISSUE THREAD

**Issue by janschumann** [puppetlabs/r10k#789]
I was just reading the changelog in order to decide whether to upgrade. The last entry is 2.5.5 and I decided to upgrade. But surprisingly the installed version was 2.6.0. Are you maintaining the changelog elsewhere?

**Comment by andersonmills** [comment]
@janschumann The CHANGELOG on the 2.6.x branch is current.

We don't necessarily keep the CHANGELOG up to date until a release. Master is currently 3.0.0-dev, and since that hasn't been released, the CHANGELOG hasn't been updated. Sorry for the confusion.

I'll add a note to this effect in the current CHANGELOG so there's not further confusion.
