### ISSUE TITLE
Git provider rugged is not functional

### ISSUE THREAD

**Issue by BarnumD** [puppetlabs/r10k#843]
I'm trying to use the rugged provider in the r10k:2.6.4 docker container.  I'm receiving the following error.
`Error while running: #<R10K::Error: Git provider 'rugged' is not functional.>`

**Comment by BarnumD** [comment]
When trying to `gem install rugged` I'm getting the following error.. (That is, after installing make, cmake, pkg-config dependencies)
```
"cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo  "
cmake: /opt/puppetlabs/puppet/lib/libcurl.so.4: no version information available (required by cmake)
cmake: /opt/puppetlabs/puppet/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by cmake)
cmake: /opt/puppetlabs/puppet/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by cmake)
cmake: /opt/puppetlabs/puppet/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)
cmake: /opt/puppetlabs/puppet/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1)

```

**Comment by underscorgan** [comment]
Hi @BarnumD , sorry for the delay in getting to this. In the short term we'll be moving to an alpine r10k container that will include the rugged gem (#903)

**Comment by Xtigyro** [comment]
@underscorgan 
Can we include it in the Puppetserver container?
I'm trying to find a way to execute `puppet generate types` after every `r10k` run in Kubernetes and because of that I'm using the Puppetserver container which also has `r10k` installed.
Probably that's not the best way forward - looking for a temporary solution until we can come up with a better one.

In the meantime - I'll add ability to do that using the default Git provider (`shellgit`).

**Comment by underscorgan** [comment]
@Xtigyro https://github.com/puppetlabs/puppetserver/pull/2223

**Comment by binford2k** [comment]
@underscorgan Is this issue resolved now?

**Comment by underscorgan** [comment]
@binford2k yep, this has been resolved for the r10k container, we were unable to do it for puppetserver container due to difficulties compiling rugged on ubuntu.
