### ISSUE TITLE
r10k doesn't use proxy for all requests

### ISSUE THREAD

**Issue by axlops** [puppetlabs/r10k#844]
At first deploy, when no cache is present, r10k doesn't use proxy to reach forge and try to connect directly : 

```
[root@~]# rm -rf /etc/puppetlabs/code/environments/*/* /var/cache/r10k/* 
[root@~]# strace /usr/local/bin/r10k deploy environment -p -v debug1 --trace 2>&1 | grep connect
read(7, "require 'puppet_forge/connection"..., 8192) = 4509
open("/usr/local/share/gems/gems/rugged-0.27.4/lib/puppet_forge/connection.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib64/gems/ruby/rugged-0.27.4/lib/puppet_forge/connection.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/share/gems/gems/r10k-2.6.4/lib/puppet_forge/connection.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection.rb", O_RDONLY|O_CLOEXEC) = 7
open("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection.rb", O_RDONLY|O_CLOEXEC) = 7
read(7, "require 'puppet_forge/connection"..., 8192) = 4179
lstat("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection.rb", {st_mode=S_IFREG|0644, st_size=4179, ...}) = 0
open("/usr/local/share/gems/gems/rugged-0.27.4/lib/puppet_forge/connection/connection_failure.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib64/gems/ruby/rugged-0.27.4/lib/puppet_forge/connection/connection_failure.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/share/gems/gems/r10k-2.6.4/lib/puppet_forge/connection/connection_failure.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection/connection_failure.rb", O_RDONLY|O_CLOEXEC) = 7
open("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection/connection_failure.rb", O_RDONLY|O_CLOEXEC) = 7
lstat("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection", {st_mode=S_IFDIR|0755, st_size=35, ...}) = 0
lstat("/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection/connection_failure.rb", {st_mode=S_IFREG|0644, st_size=916, ...}) = 0
open("/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/connection.rb", O_RDONLY|O_CLOEXEC) = 7
open("/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/connection.rb", O_RDONLY|O_CLOEXEC) = 7
lstat("/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/connection.rb", {st_mode=S_IFREG|0644, st_size=15295, ...}) = 0
connect(7, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(7, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(8, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(8, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(8, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.2")}, 16) = 0
connect(8, {sa_family=AF_INET, sin_port=htons(22), sin_addr=inet_addr("192.168.1.9")}, 16) = 0
connect(8, {sa_family=AF_INET, sin_port=htons(3128), sin_addr=inet_addr("10.10.1.5")}, 16) = 0
connect(8, {sa_family=AF_INET, sin_port=htons(3128), sin_addr=inet_addr("10.10.1.5")}, 16) = 0
connect(8, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.2")}, 16) = 0
connect(8, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("52.10.130.237")}, 16) = 0
```

In this example, 10.10.3.2 is a local DNS server, 192.168.1.9 is a local gitlab server, 10.10.1.5 is the HTTP/HTTPS proxy).
Network is filtered, only proxy requests are allowed, and this last connect() call on 52.10.130.237 (puppet forge api) fails with timeout. In this log it seems that there are some requests which where correctly executed through proxy but not this one to puppet forge api.

r10k configuration file:

```
cachedir: '/var/cache/r10k'
proxy: 'http://10.10.1.5:3128'

sources:
  infrastructure:
    remote: 'git@xxxxxxxxxxx/puppet-control-repo.git'
    basedir: '/etc/puppetlabs/code/environments'

git:
  provider: 'rugged'
  private_key: '/etc/puppetlabs/r10k/gitlab_rsa'
forge:
  proxy: 'http://10.10.1.5:3128'
```

If I open the network (disable filter) and let the first deploy finish, and then enable network filtering to force the use of proxy and re run **r10k deploy environment -p** I don't see any following requests directly to puppet forge API IP address. There are requests to puppetforge but they are going through proxy.
It s like since there are already cached files and installed environments, some requests to puppet forge are not required.
I didn't try yet another deploy -p with new modules from puppet forge, maybe it will fail too.

**Comment by axlops** [comment]
ruby stack trace : 
```
[2018-09-09 11:58:12 - DEBUG1] Downloading puppetlabs-apt-6.0.0 from https://forgeapi.puppetlabs.com/ to /tmp/d20180909-27512-13n427e/puppetlabs-apt-6.0.0.tar.gz


[2018-09-09 12:00:20 - ERROR] Connection timed out - connect(2)
/usr/share/ruby/net/http.rb:878:in `initialize'
/usr/share/ruby/net/http.rb:878:in `open'
/usr/share/ruby/net/http.rb:878:in `block in connect'
/usr/share/ruby/timeout.rb:52:in `timeout'
/usr/share/ruby/net/http.rb:877:in `connect'
/usr/share/ruby/net/http.rb:862:in `do_start'
/usr/share/ruby/net/http.rb:851:in `start'
/usr/share/ruby/net/http.rb:1373:in `request'
/usr/share/ruby/net/http.rb:1131:in `get'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/connection/connection_failure.rb:9:in `call'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
/usr/local/share/gems/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/middleware/symbolify_json.rb:64:in `call'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
/usr/local/share/gems/gems/puppet_forge-2.2.9/lib/puppet_forge/v3/release.rb:27:in `download'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/forge/module_release.rb:97:in `download'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/forge/module_release.rb:82:in `install'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/module/forge.rb:149:in `install'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/module/forge.rb:48:in `sync'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/deploy/environment.rb:124:in `visit_module'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/visitor.rb:24:in `visit'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/module/base.rb:82:in `accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/puppetfile.rb:151:in `block (2 levels) in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/puppetfile.rb:150:in `each'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/puppetfile.rb:150:in `block in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/deploy/environment.rb:114:in `visit_puppetfile'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/visitor.rb:24:in `visit'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/puppetfile.rb:149:in `accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/environment/base.rb:100:in `block in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/deploy/environment.rb:96:in `visit_environment'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/visitor.rb:24:in `visit'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/environment/base.rb:99:in `accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/source/base.rb:64:in `block (2 levels) in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/source/base.rb:63:in `each'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/source/base.rb:63:in `block in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/deploy/environment.rb:74:in `visit_source'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/visitor.rb:24:in `visit'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/source/base.rb:62:in `accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/deployment.rb:108:in `block (2 levels) in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/deployment.rb:107:in `each'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/deployment.rb:107:in `block in accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/deploy/environment.rb:59:in `visit_deployment'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/visitor.rb:24:in `visit'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/deployment.rb:106:in `accept'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/deploy/environment.rb:37:in `call'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/runner.rb:33:in `call'
/usr/local/share/gems/gems/r10k-2.6.4/lib/r10k/action/cri_runner.rb:67:in `call'
/usr/local/share/gems/gems/cri-2.6.1/lib/cri/command_dsl.rb:223:in `block in runner'
/usr/local/share/gems/gems/cri-2.6.1/lib/cri/command.rb:298:in `call'
/usr/local/share/gems/gems/cri-2.6.1/lib/cri/command.rb:298:in `run_this'
/usr/local/share/gems/gems/cri-2.6.1/lib/cri/command.rb:251:in `run'
/usr/local/share/gems/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/usr/local/share/gems/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/usr/local/share/gems/gems/r10k-2.6.4/bin/r10k:7:in `<top (required)>'
/usr/local/bin/r10k:23:in `load'
/usr/local/bin/r10k:23:in `<main>'
```

**Comment by axlops** [comment]
I just found a workaround : adding https_proxy environment variable allow to use proxy for those missing requests : 
```
https_proxy=https://10.10.1.5:3128 /usr/local/bin/r10k deploy environment -p
```

**Comment by matejzero** [comment]
One more gut with this problem here.

**Comment by kenyon** [comment]
Same problem here with r10k 3.0.3. Setting the environment variables is not a good enough workaround because I have sources that cannot go via a proxy, whereas Forge access does need to go through the proxy.

**Comment by kenyon** [comment]
Seems also that r10k is not using the proxy correctly. When I have the git.proxy setting in r10k.yaml set to my proxy, I always get HTTP error 407 when doing `r10k deploy display --detail --fetch`. Whereas when I remove that setting from r10k.yaml and have http_proxy environment variable set to the same value, it works correctly.

Having to work behind a proxy like this is completely maddening...

**Comment by negacion** [comment]
Any news on that issue ? Version 3.3.0 still does not work.

I can't see the point of having a proxy setting in r10k.yaml file if it is ignored...

**Comment by Raskil** [comment]
I see the same issue with bolt on a "bolt puppetfile install" with a configured proxy. If I do a tcpdump some requests are send via proxy and some are send directly to the forge (which is not possible in my environment). I can work around that by using setting http_proxy, https_proxy and no_proxy environment variables (then all requests go through the proxy).

**Comment by smoeding** [comment]
I just encountered the same problem here. I use `r10k deploy environment -v -p` to deploy modules from the Puppetfile. My http-proxy is defined in `r10k.yaml`. I have no git-proxy as I need to access local repositories on the LAN.

I have reproducible failures with 3 modules from the Forge: `derdanne-nfs`, `deric-zookeeper` and `openstack-ceph`. All other modules work fine.

These three modules have one thing in common: these are the only modules in my setup that are loaded from the forge and include a `.git` directory in the module. Maybe this triggers a codepath in r10k where the proxy is ignored?

**Comment by matejzero** [comment]
This is still a problem and we are still waiting for a solution.

**Comment by Magisus** [comment]
Hm, looks like there's a whole snarl of problems here with the proxy. To make matters worse, recent versions of Rugged/libgit2 (used by default in PE) completely changed the way they do proxies, so upgrading there is going to require more mucking around with this. Thanks for all the info in here about what works and what doesn't!

**Comment by Magisus** [comment]
I started looking into this a bit today, and was having a hard time reproducing any proxy issues.

Some notes:
* As the original poster said, once the modules have been downloaded on the first run, we no longer try to reach out to the forge, so any proxy issues there would disappear after the first deploy, until Puppetfile content changes and triggers new module downloads.
* I tried to use the modules @smoeding mentions, which had a git dir in his install. These modules behave the same as all other modules for me, and notably no longer seem to install `.git` dirs, even when I tried an old version of the module. Either they've all been purged from the Forge, or I wasn't trying the right thing. @smoeding do you know what exact versions of those modules failed for you?
* In r10k 3.3.1, we updated the version of the `puppet_forge` gem we use, which would have also pulled in a faraday update that supposedly fixed some proxy issues, see [this note](https://github.com/puppetlabs/forge-ruby/blob/main/CHANGELOG.md#v231---2019-11-15). It's a little hard to tell from these anecdotes which of these issues still applies since that update (released in late 2019).

If anyone is still struggling with this in _current_ r10k, can you provide some info on what _exactly_ is failing, including which specific modules fail to download and which of the various proxy settings you have configured (global, forge, git, per-repo)?

**Comment by smoeding** [comment]
@mwaggett It seems the latest modules don't have the `.git` subdirectory any more. An example of an old module where the `.git` directory is included in the download would be `deric-zookeeper` in version 1.0.0: https://forge.puppet.com/modules/deric/zookeeper/1.0.0
We have updated our workflow in the meantime so I won't be able to verify these problems any more.

**Comment by Magisus** [comment]
Thanks! I didn't try 1.0.0, I'll give it a shot. Even if we can only fix that edge case, it'll be progress, and it might help us find other areas where the proxy handling is bad.

**Comment by Magisus** [comment]
I was able to test with the forge module containing the git dir.

The [special code path](https://github.com/puppetlabs/r10k/blob/a65ca0337aa9ae7e3fb349c1f97aebc8dece4b45/lib/r10k/module/forge.rb#L143-L145) that is followed causes forge modules with git dirs to be reinstalled on every run, because r10k makes the (erroneous) assumption that the module is being converted from a git-based module to a forge module, and so reinstalls it to "convert" it. 

In my experiment, we correctly use the configured proxy in this case. Configuring a bad proxy, I get:
```
Unable to connect to https://forgeapi.puppetlabs.com (using proxy http://127.0.0.1:3127) (for request /v3/modules/deric-zookeeper): Couldn't connect to server
```
Though I would argue that the behavior to reinstall on every run is its own bug.

**Comment by Magisus** [comment]
@matejzero you're the most recent commenter who was still having issues with proxies. Are those still occurring? If so, can you describe what you're seeing, and with which versions of `r10k`, `puppet_forge`, and `faraday`?

**Comment by matejzero** [comment]
I updated r10k gem to latest version:
- r10k (3.10.0)
- puppet_forge (2.3.0)
- faraday (0.13.1)

I have in my r10k.yaml config the following proxy settings:
```
forge:
  baseurl: 'https://forge.puppet.com'
  proxy: 'http://proxy.example.tld:3128'
```

When I add a forge module to Puppetfile, it won't pull it through the proxy so it times out:
```
ERROR	 -> Error during concurrent deploy of a module: Unable to connect to https://forge.puppet.com (for request /v3/files/puppetlabs-concat-7.0.0.tar.gz): execution expired
ERROR	 -> Unable to connect to https://forge.puppet.com (for request /v3/files/puppetlabs-concat-7.0.0.tar.gz): execution expired
```

If I manually set https_proxy env variable on run r10k with HTTPS_PROXY prefix set, it will correctly pull the module down and install it.

**Comment by Magisus** [comment]
Interesting, this example definitely works as expected for me. I set up my r10k file the way you did, but with a faulty proxy (since my machines _can_ use the normal URL). It fails immediately when trying to download a module when it tries to use the bad proxy.

**Do you have any other environment variables set generally in the background that could be interfering here?** We look at a [series of env vars](https://github.com/puppetlabs/r10k/blob/7f5bbb14cdbbae4fa7c48ae9881a83fdbb864c3c/lib/r10k/settings.rb#L250-L254) by default when trying to detect proxy configuration, though your `forge.proxy` setting should override that.

To walk through the logic that is used:
* The forge-specific setting [inherits](https://github.com/puppetlabs/r10k/blob/7f5bbb14cdbbae4fa7c48ae9881a83fdbb864c3c/lib/r10k/settings.rb#L123) its default from the global setting, but can be overridden.
* When the app is set up, we call a series of initializers. The global initializer calls the initializer for each subsection, including [forge](https://github.com/puppetlabs/r10k/blob/7f5bbb14cdbbae4fa7c48ae9881a83fdbb864c3c/lib/r10k/initializers.rb#L40).
* the forge initializer takes the proxy value out of that subsection and [passes](https://github.com/puppetlabs/r10k/blob/7f5bbb14cdbbae4fa7c48ae9881a83fdbb864c3c/lib/r10k/initializers.rb#L68) it to the `PuppetForge.connection`, which comes from the `puppet_forge` gem.
* Setting the proxy [there](https://github.com/puppetlabs/forge-ruby/blob/abcf7dc4f0da18d033eee219b662f86e5af8ca9b/lib/puppet_forge/connection.rb#L44-L47) is pretty simple. 
 
**However**, there is some kind of [odd logic](https://github.com/puppetlabs/forge-ruby/blob/abcf7dc4f0da18d033eee219b662f86e5af8ca9b/lib/puppet_forge/connection.rb#L31-L37) that happens when `authorization` is also configured on that connection. We [set this](https://github.com/puppetlabs/r10k/blob/7f5bbb14cdbbae4fa7c48ae9881a83fdbb864c3c/lib/r10k/action/runner.rb#L75-L88) when a PE license is detected. Do you have a PE license in your environment? Curious if there's still a bug there somewhere... 

In the meantime I'll look if I can get my hands on a dummy PE license for testing...

**Comment by Magisus** [comment]
Oh man, I just had a thought. Are you using gem (non-PE) r10k, and rugged 1.0+? There are known issues with proxies in Rugged 1.0+ that we haven't sorted out yet. We're pinned to the older versions in PE, which is what I was testing with...

I'll need to retest this with gem r10k.

**Comment by matejzero** [comment]
Any update on this front? I tried looking at rugged gem, but it doesn't seem to be installed on my system.

```
bash-4.2$ /opt/puppetlabs/puppet/bin/gem list | grep rugged
bash-4.2$ 
```

**Comment by Magisus** [comment]
Okay, that probably doesn't matter anyway, since the issue you're having is with Forge modules, right? And since it sounds like you're not a Puppet Enterprise user (PE would definitely be using rugged), there goes my theory about the license interfering.

I'll try this with gem-installed r10k and see what I can find (sorry it's been very busy around here lately and I haven't gotten back to this yet).
