### ISSUE TITLE
Can r10k deal with dependency in Modulefile?

### ISSUE THREAD

**Issue by rvora** [puppetlabs/r10k#89]
It looks like r10k ignores dependencies of modules listed in Puppetfile. Is this the expected behavior?

If yes, then r10k is not a drop-in-replacement for librarian-puppet and in case is it possible to use librarian-puppet when 'r10k deploy environment -p' is called?

**Comment by rvora** [comment]
I see --ignore-dependencies being used in lib/r10k/module/forge.rb. So that explains why module's dependencies are ignored by 'puppet module install'. I guess I would like to know why --ignore-dependecies was chosen as the default and only behavior and how should one figure out all the dependencies without going through trial-and-error iterations.

**Comment by adrienthebo** [comment]
- Is r10k a drop-in replacement for librarian-puppet?

Unfortunately no, not yet. Since the README was misleading about this I've updated it accordingly: https://github.com/adrienthebo/r10k/commit/29f9471c04e7f91b9d0e8f2243a71a25664738cf
- Why are forge module dependencies ignored?

A forge module may bring in a dependency that conflicts with either another forge module or a git module, which could create some very strange interactions. Since modules installed from Git can't install module dependencies it's more consistent to not handle dependencies rather than do it for some modules and risk conflicts.
- Can librarian-puppet be used when `r10k deploy environment -p` is  called?

Theoretically it's possible. I've looked at some of the librarian API and it looked like it wouldn't be very straightforward to do, but if someone is willing to look into handling this then I would be thrilled.
- How can dependencies be  resolved for a Puppetfile?

I believe that you can use librarian-puppet's lockfile to synthesize this information, although it may require a bit of manual work.
- When will dependency resolution be implemented?

It depends on a number of things. First off there's a library for dependency resolution that should be slotted in and can provide dependency resolution in one pass, but I'm waiting for it to be released so it can be depended. It also depends on how much free time I have - I'm not paid to work on r10k so I have to work on it on my evenings and weekends. While I understand that it's painful to not have this feature the reality is that I simply don't have the resources to implement this by myself in the immediate future.

**Comment by rvora** [comment]
Thanks Adrien for the detailed response. It makes sense.

Before anything else, thanks very much for your generous work on r10k. r10k makes it easy to implement dynamic environments - the way all new puppet installs should be done in my view.

I would think that librarian-puppet will also fail on the kind of conflicting transient dependency problems you are talking about though I have not tried it out to verify.

I am not a big ruby guy but I'll take a stab at adding in hook to call out librarian-puppet directly as an optional feature and if I can figure it out I'll send you a pull request. Without ability to deal with transient dependencies, the process of figuring out full Puppetfile is non-trivial and error prone.

I understand the transient dependency issues - that should be considered a bug in the modules concerned and not cripple r10k or librarian-puppet.

**Comment by jantman** [comment]
I _believe_ this is a duplicate of Issue #38 "Add support for installing module dependencies"

**Comment by adrienthebo** [comment]
@jantman thanks for noting this; @rvora if #38 doesn't cover all your concerns let me know and we can copy comments. In the mean time I'm going to close this to reduce issue duplication.

**Comment by rvora** [comment]
That's fine.
